### PR TITLE
fix: schema error in linter-settings

### PR DESCRIPTION
**Pull request by ejain**
Screen Shot 2021-02-19 at 10 03 02 PM

### CODE REVIEW

**Comment by ejain** [comment]
Looks like YAML doesn't support dots in keys, so this doesn't work for anything but standard packages... Not sure where the schema is defined?

**Comment by ejain** [comment]
Looks like the schema is defined in https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/golangci-lint.json.

**Comment by ldez** [comment]
Hello, the problem seems related to viper https://github.com/spf13/viper/issues/324

**Comment by ldez** [comment]
after more investigation, the fact to use a list instead of a map in the YAML is a hack to be able to use key's name with a dot.

**Comment by ldez** [comment]
So the schema is right, the configuration examples also, but both are not compatible.

The list syntax is currently the only way to define the configuration, because of a bug inside viper.

I think you can open an issue for tracking this.

I will close this PR.

**Pull request closed without merging**
