### PR TITLE
gci: fix `custom-order` setting and upgrade to 0.6.1

### PR DESCRIPTION
**Pull request by Dreamacro**
Fix `custom-order` setting not work.

And upgrade to 0.6.1

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

We have a bot that manages updates of the linters.

thanks anyway

**Comment by Dreamacro** [comment]
@ldez but this PR contains another fix, not related to upgrade

**Comment by ldez** [comment]
That's not how it works.

The bot will create a PR and inside this PR we (the golangci-lint team) will update the code inside the PR of the bot.

**Comment by Dreamacro** [comment]
@ldez I could push force the commit that only contains the fix. Or do you think you need to open a new PR?

**Comment by ldez** [comment]
you can open a PR with only the fix.

**Pull request closed without merging**
