### PR TITLE
doc: Add Wingie Enuygun Group to Trusted By page

### PR DESCRIPTION
**Pull request by phpdev**

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

are you an employee of this company?

**Comment by phpdev** [comment]
Yes, I am an employee of Wingie Enuygun Group.

**Comment by ldez** [comment]
I'm happy that golangci-lint helps your company :heart: 

This page is a type of free ad, so we will [remove this page](https://github.com/golangci/golangci-lint/pull/4857).

It's not against you or your company, but currently, the financial support of golangci-lint is about $6... (You can check that here: https://opencollective.com/golangci-lint)
I think $6 is not fair, I hope that individuals and mainly companies will help us financially to have a sustainable ecosystem.

**Comment by ldez** [comment]
I hope you understand our decision.

**Pull request closed without merging**
