### PR TITLE
importas: new option `no-extra-aliases`

### PR DESCRIPTION
**Pull request by butuzov**
Adds `no-extra-aliases` option to `importas` linter. (added in (https://github.com/julz/importas/commit/27e0a5d4dee270c88e73ce808fce24fad723ed30))

### CODE REVIEW

**Comment by butuzov** [comment]
Waiting for taged release.

**Comment by ldez** [comment]
@butuzov there is no tag for this linter, so it's useless to wait for a release.

**Comment by butuzov** [comment]
@ldez I wrote him message and can wait for a few days, if not - I will pin it to the last commit.

**Comment by ldez** [comment]
I don't see any public issue about the fact to create a tag.
At least, can you update the dependency even if you will update it again later?

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
