### PR TITLE
debug gci commit

### PR DESCRIPTION
**Pull request by daixiang0**
Debug https://github.com/golangci/golangci-lint/pull/3674 since no MAC or WIN machine.

### CODE REVIEW

**Comment by alexandear** [comment]
I have macOS and Windows machines, so can test this bump.

**Comment by daixiang0** [comment]
@alexandear thank you very much, now we can confirm `c19c1aa5634e` bring this panic.

**Comment by daixiang0** [comment]
Run codes with online playground and find root cause, https://github.com/daixiang0/gci/pull/151 fix this.

**Comment by ldez** [comment]
you can use your own fork to it.

**Pull request closed without merging**
