### PR TITLE
Fix typo in gometalinter comparison example

### PR DESCRIPTION
**Pull request by bvwells**
Fix typo in gometalinter comparison example.

### CODE REVIEW

**Comment by jirfag** [comment]
thank you! I'm waiting for CLA to merge

**Comment by bvwells** [comment]
No problems @jirfag!

**Comment by bvwells** [comment]
@jirfag, it looks like golangci-lint also supports excludes on the command line (```--exclude=<default golangci-lint excludes>```). I was thinking about adding this to the gometalinter example comparison. What do you think?

**Comment by jirfag** [comment]
these excludes are used by default, even without an explicit argument.

**Comment by bvwells** [comment]
I see what you mean. Thanks for the clarification.

**Pull request merged**
