### PR TITLE
Support go1.13

### PR DESCRIPTION
**Pull request by jirfag**
Setup Travis CI to run on go 1.12 and 1.13.
Update info about go versions in README.
Rebuild go.mod,go.sum on go1.13.

Thank you for the pull request!

### CODE REVIEW

**Comment by freeformz** [comment]
FWIW: w/o the go.mod changes here I can't `go get github.com/golangci/golangci-lint`, so I hope a new release happens soon.

**Comment by freeformz** [comment]
Additional note - Even with golangci-lint @ 1.17.1
```console
$ go get github.com/golangci/golangci-lint/cmd/golangci-lint
go: github.com/golangci/golangci-lint@v1.17.1 requires
        github.com/go-critic/go-critic@v0.0.0-20181204210945-1df300866540: invalid pseudo-version: does not match version-control timestamp (2019-05-26T07:48:19Z)
```

**Comment by zikaeroh** [comment]
Yes, this PR predates 1.17.1. You'd need to get `@master` to pick this up, or wait for the next tagged release.

**Comment by freeformz** [comment]
@zikaeroh Well master....

```console
go get github.com/golangci/golangci-lint/cmd/golangci-lint@master
go: finding github.com/golangci/golangci-lint/cmd master
go: finding github.com/golangci/golangci-lint/cmd/golangci-lint master
go: finding github.com/golangci master
go: finding github.com/golangci/golangci-lint master
go: finding github.com master
go: downloading github.com/golangci/golangci-lint v1.17.2-0.20190909185456-6163a8a79084
go: extracting github.com/golangci/golangci-lint v1.17.2-0.20190909185456-6163a8a79084
# github.com/golangci/golangci-lint/pkg/lint
../../go/pkg/mod/github.com/golangci/golangci-lint@v1.17.2-0.20190909185456-6163a8a79084/pkg/lint/load.go:278:3: unknown field 'Logf' in struct literal of type "golang.org/x/tools/go/packages".Config
```

**Comment by freeformz** [comment]
PS: That is because the replacements need to be pulled forward into our project.

**Comment by tariq1890** [comment]
Looking forward to a new release from this :)

**Comment by jirfag** [comment]
I can't get rid of replacements until my pull requests to upstreams are merged. But I've changed replaced x/tools to be compatible with the replacement.
Now `GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@95d5b2c` works. And today-tomorrow I will make a new release.

**Pull request merged**
