### PR TITLE
add nevernester linter

### PR DESCRIPTION
**Pull request by raffepaffe**
Hi.

Nevernester is a Go linter that finds nesting in functions. Many levels of nesting reduce readability and adds cognitive load.

https://github.com/raffepaffe/nevernester

First time contributor, please let me know if something is missing in the pr.

### CODE REVIEW

**Comment by ldez** [comment]
In order for a pull request adding a linter to be reviewed, the linter and the PR must follow some requirements.

- [ ] The CLA must be signed

### Pull Request Description

- [ ] It must have a link to the linter repository.
- [ ] It must provide a short description of the linter.

### Linter

- [ ] It must not be a duplicate of another linter or a rule of a linter. (the team will help to verify that)
- [ ] It must have a valid license (AGPL is not allowed) and the file must contain the required information by the license, ex: author, year, etc.
- [ ] The linter repository must have a CI and tests.
- [ ] It must use [`go/analysis`](https://golangci-lint.run/contributing/new-linters/).
- [ ] It must have a valid tag, ex: `v1.0.0`, `v0.1.0`.
- [ ] It must not contain `init()`.
- [ ] It must not contain `panic()`, `log.fatal()`, `os.exit()`, or similar.
- [ ] It must not have false positives/negatives. (the team will help to verify that)
- [ ] It must have tests inside golangci-lint.

### The Linter Tests Inside Golangci-lint

- [ ] They must have at least one std lib import.
- [ ] They must work with `T=<name of the linter test file>.go make test_linters`. (the team will help to verify that)

### `.golangci.reference.yml`

- [ ] The linter must be added to the list of available linters (alphabetical case-insensitive order).
    - `enable` and `disable` options
- [ ] If the linter has a configuration, the exhaustive configuration of the linter must be added (alphabetical case-insensitive order)
    - The values must be different from the default ones.
    - The default values must be defined in a comment.
    - The option must have a short description.

### Others Requirements

- [ ] The files (tests and linter) inside golangci-lint must have the same name as the linter.
- [ ] The `.golangci.yml` of golangci-lint itself must not be edited and the linter must not be added to this file.
- [ ] The linters must be sorted in the alphabetical order (case-insensitive) in the `Manager.GetAllSupportedLinterConfigs(...)` and `.golangci.reference.yml`.
- [ ] The load mode (`WithLoadMode(...)`):
    - if the linter doesn't use types: `goanalysis.LoadModeSyntax`
    - `goanalysis.LoadModeTypesInfo` required `WithLoadForGoAnalysis()` in the `Manager.GetAllSupportedLinterConfigs(...)`
- [ ] The version in `WithSince(...)` must be the next minor version (`v1.X.0`) of golangci-lint.

### Recommendations

- [ ] The linter should not use SSA. (currently, SSA does not fully support generics)
- [ ] The linter repository should have a readme and linting.
- [ ] The linter should be published as a binary. (useful to diagnose bug origins)

---

The golangci-lint team will edit this comment to check the boxes before and during the review.

The code review will start after the completion of those checkboxes (except for the specific items that the team will help to verify).

If the author of the PR is a member of the golangci-lint team, he should not edit this message.

**This checklist does not imply that we will accept the linter.**

**Comment by raffepaffe** [comment]
Hi, realised that I missed to link to the linter. Sorry about that. Nevernester can be found at [here](https://github.com/raffepaffe/nevernester)

**Comment by ldez** [comment]
This linter feels like a duplicate of [gocognit](https://github.com/uudashr/gocognit) and it's really near `cyclop` or `gocyclo`.

**Comment by raffepaffe** [comment]
Ohh, no! 
I was not aware of gocognito and what I have done seams to be close to some part (nesting) that is done there. 
The difference seams to be that I only focus on the nesting part and that you can set the max nesting level that you want. I can't see that you can do it in gocognito.

I don't know if this is different enough? If you feel it's not, I will close the PR.
Thanks for your quick feedback.

**Comment by alexandear** [comment]
Additionally, [`nestif`](https://github.com/nakabonne/nestif) provides similar functionality.

**Comment by raffepaffe** [comment]
Ok, thanks for your feedback.

**Pull request closed without merging**
