### PR TITLE
Use upstream gocyclo.

### PR DESCRIPTION
**Pull request by ldez**
Gocyclo has been updated https://github.com/fzipp/gocyclo/commits/main

we don't need  a fork anymore https://github.com/golangci/gocyclo

### CODE REVIEW

**Review by invidian — COMMENTED** [review]
LGTM, but I'd pull code from #1741 as it simplifies some code too.

**Comment by ldez** [comment]
@invidian you can suggest changes in this PR if you want.

**Comment by ldez** [comment]
@invidian I applied your suggestions.

**Review by invidian — APPROVED** [review]
Cool!

**Review by ernado — APPROVED** [review]
LGTM

**Pull request merged**
