### PR TITLE
build(deps): bump github.com/timonwong/logrlint from 0.1.0 to 0.4.0

### PR DESCRIPTION
**Pull request by timonwong**
https://github.com/timonwong/logrlint/compare/v0.1.0...v0.3.0

Notable changes:
- fix a fales positive for dotdotdot args
- add support to [klog](https://github.com/kubernetes/klog)
- add config flags `disableall`, `disable` and `enable`

### CODE REVIEW

**Comment by ldez** [comment]
FYI in the basic case, when a linter requires an update we let the dependabot handle that.

**Comment by ldez** [comment]
I would like to propose a better configuration:
```yml
linters-settings:
  logrlint:
    logr: true
    klog: true
```

**Comment by ldez** [comment]
Why your PR is on draft?

**Comment by timonwong** [comment]
> Why your PR is on draft?

@ldez It's still working in progress right now

**Comment by ldez** [comment]
> It's still working in progress right now

It's better to open a PR when the PR is ready.

**Comment by ldez** [comment]
Also, your linter name is based on `logr`, now your are trying to integration `klog`, `zap`.

I think it can be better to create another linter with a better name that fits with the goal of your linter, and deprecate the previous linter.

**Comment by timonwong** [comment]
Thanks, I'll close this PR for now. When it's ready, I'll open a new PR for review

**Pull request closed without merging**
