### PR TITLE
Add verifyiface linter

### PR DESCRIPTION
**Pull request by dcu**
repo: https://github.com/dcu/verifyiface
verifies interface compliance: https://github.com/uber-go/guide/blob/master/style.md#verify-interface-compliance

### CODE REVIEW

**Comment by ldez** [comment]
In order for a pull request adding a linter to be reviewed, the linter and the PR must follow some requirements.

### Pull Request Description

- [ ] It must have a link to the linter repository.
- [ ] It must provide a short description about the linter.

### Linter

- [ ] It must not be a duplicate of another linter or a rule of a linter. (the team will help to verify that)
- [ ] It must have a valid license and the file must contain the required information by the license, ex: author, year, etc.
- [ ] It must use [`go/analysis`](https://golangci-lint.run/contributing/new-linters/).
- [ ] It must have a valid tag, ex: `v1.0.0`, `v0.1.0`.
- [ ] It must not contain `init()`.
- [ ] It must not contain `panic()`, `log.fatal()`, `os.exit()`, or similar.
- [ ] It must not have false positives/negatives. (the team will help to verify that)
- [ ] It must have tests inside golangci-lint.

### The Linter Tests Inside Golangci-lint

- [ ] They must have at least one std lib import.
- [ ] They must work with `T=<name of the linter test file>.go make test_linters`. (the team will help to verify that)

### `.golangci.example.yml`

- [ ] The linter must be added to the list of available linters (alphabetical case-insensitive order).
  - `enable` and `disable` options
- [ ] If the linter has a configuration, the exhaustive configuration of the linter must be added (alphabetical case-insensitive order)
  - The values must be different from the default ones.
  - The default values must be defined in a comment.
  - The option must have a short description.

### Others Requirements

- [ ] The files (tests and linter) inside golangci-lint must have the same name as the linter.
- [ ] The `.golangci.yml` of golangci-lint itself must not be edited and the linter must not be added to this file.
- [ ] The linters must be sorted in the alphabetical order (case-insensitive) in the `Manager.GetAllSupportedLinterConfigs(...)` and `.golangci.example.yml`.
- [ ] The load mode (`WithLoadMode(...)`):
  - if the linter doesn't use types: `goanalysis.LoadModeSyntax`
  - `goanalysis.LoadModeTypesInfo` required `WithLoadForGoAnalysis()` in the `Manager.GetAllSupportedLinterConfigs(...)`
- [ ] The version in `WithSince(...)` must be the next minor version (`v1.X.0`) of golangci-lint.

### Recommendations

- [ ] The linter should not use SSA. (currently, SSA does not support generics)
- [ ] The linter repository should have a CI, tests, a readme and linting.
- [ ] The linter should be published as a binary. (useful to diagnose bug origins)

---

The golangci-lint team will edit this comment to check the boxes before and during the review.

**This checklist does not imply that we will accept the linter.**

**Comment by ldez** [comment]
My opinion about this linter:
- The rule defined in Uber's style guide has conditions but this linter will report something in all contexts, so it will produce a lot of false positives.
- I think that the "Good" example in the style guide is a bad practice because IMHO checking the interface is more related to tests than the code by itself.

**Comment by dcu** [comment]
I don't agree it's a bad practice to verify interface compliance. Tests are good but if the compiler can help it's better otherwise we'd be using something like python.
I also don't agree there are false positives for this linter, at least not strictly. But I agree there would be too many results that could not be useful (I assume this is what you call "false positive")

In any case, I updated the behavior of the linter and now by default it only reports when the interface is used in a type assertion which is the case where more code is broken because of this

I also updated the PR to fix some of the items in the check list

**Comment by ldez** [comment]
> I don't agree it's a bad practice to verify interface compliance. Tests are good but if the compiler can help it's better otherwise we'd be using something like python.

Maybe I was not clear, but my opinion is that this kind of check must be placed in tests files `xx_test.go` not in the code `xx.go` files.

> I also don't agree there are false positives for this linter, at least not strictly. But I agree there would be too many results that could not be useful (I assume this is what you call "false positive")

The reports will drive users to fix non-existing problems, so for me, this is a kind of false positive.

**Comment by dcu** [comment]
> > I don't agree it's a bad practice to verify interface compliance. Tests are good but if the compiler can help it's better otherwise we'd be using something like python.
> 
> Maybe I was not clear, but my opinion is that this kind of check must be placed in test files (`xx_test.go`) not in the code files (`xx.go`). Because those global variables are useless for the application or libraries, they will take the memory unnecessarily.
> 
I see. From what I understand those _ variables are stripped by the compiler so they won't take memory at all 

> > I also don't agree there are false positives for this linter, at least not strictly. But I agree there would be too many results that could not be useful (I assume this is what you call "false positive")
> 
> The reports will drive users to fix non-existing problems, so for me, this is a kind of false positive.
> 
> Some rules of a style guide require human choices because humans can understand the design context. Linters are here to detect style rules and bugs that in 99% of cases don't require design choice to be applied.
> 
> IMO, an interface compliance check is useful in 1% of cases.
> 
yeah this is about preventing issues, not fixing them

> Note:
> 
> Your linter doesn't work well inside golangci-lint.

I'll take a look, thanks

**Comment by ldez** [comment]
I tried your linter on several projects and it confirms what I thought: the linter reports 99,99% of false positives and inaccurate interface suggestions, it is also panicking.

<details>

```console
 $ ./golangci-lint run
ERRO [runner] Panic: verifyiface: package "genstatic" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference: goroutine 24474 [running]:
runtime/debug.Stack()
        /home/ldez/.gvm/gos/go1.18.2/src/runtime/debug/stack.go:24 +0x65
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
        /home/ldez/sources/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:101 +0x155
panic({0x1499ea0, 0x1f15f70})
        /home/ldez/.gvm/gos/go1.18.2/src/runtime/panic.go:838 +0x207
go/types.(*Interface).Empty(0x874745?)
        /home/ldez/.gvm/gos/go1.18.2/src/go/types/interface.go:120 +0x14
go/types.Implements({0x18397b0, 0xc00bad6e00}, 0x4ac0628?)
        /home/ldez/.gvm/gos/go1.18.2/src/go/types/api.go:460 +0x2f
github.com/dcu/verifyiface/analyzer.findAllImplementations.func1({0x1839198?, 0xc00baacfa0?})
        /home/ldez/sources/go/pkg/mod/github.com/dcu/verifyiface@v0.0.0-20220515234650-cff5d584ddf8/analyzer/analyzer.go:206 +0x4b2
go/ast.inspector.Visit(0xc0005e6400, {0x1839198?, 0xc00baacfa0?})
        /home/ldez/.gvm/gos/go1.18.2/src/go/ast/walk.go:387 +0x31
go/ast.Walk({0x1836800?, 0xc0005e6400?}, {0x1839198?, 0xc00baacfa0?})
        /home/ldez/.gvm/gos/go1.18.2/src/go/ast/walk.go:52 +0x62
go/ast.Walk({0x1836800?, 0xc0005e6400?}, {0x18395f8?, 0xc00bad08c0?})
        /home/ldez/.gvm/gos/go1.18.2/src/go/ast/walk.go:328 +0x1b3b
go/ast.Walk({0x1836800?, 0xc0005e6400?}, {0x1839120?, 0xc00bad0980?})
        /home/ldez/.gvm/gos/go1.18.2/src/go/ast/walk.go:345 +0x21ea
go/ast.walkDeclList({0x1836800, 0xc0005e6400}, {0xc00a298600?, 0x14, 0xc0005e6400?})
        /home/ldez/.gvm/gos/go1.18.2/src/go/ast/walk.go:38 +0x91
go/ast.Walk({0x1836800?, 0xc0005e6400?}, {0x1839058?, 0xc00baa6700?})
        /home/ldez/.gvm/gos/go1.18.2/src/go/ast/walk.go:367 +0x1890
go/ast.Inspect(...)
        /home/ldez/.gvm/gos/go1.18.2/src/go/ast/walk.go:399
github.com/dcu/verifyiface/analyzer.findAllImplementations(0xc007ce8c30?, {0xc007a10ad0?, 0x1?, 0x1?})
        /home/ldez/sources/go/pkg/mod/github.com/dcu/verifyiface@v0.0.0-20220515234650-cff5d584ddf8/analyzer/analyzer.go:170 +0x265
github.com/dcu/verifyiface/analyzer.run(0xc007ce8c30)
        /home/ldez/sources/go/pkg/mod/github.com/dcu/verifyiface@v0.0.0-20220515234650-cff5d584ddf8/analyzer/analyzer.go:68 +0x219
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc007270f70)
        /home/ldez/sources/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:187 +0x9c4
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
        /home/ldez/sources/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:105 +0x1d
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0025230e0, {0x1621c10, 0xb}, 0xc0069d8f48)
        /home/ldez/sources/go/src/github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:111 +0x4a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc00088d260?)
        /home/ldez/sources/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:104 +0x85
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc007270f70)
        /home/ldez/sources/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb4
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
        /home/ldez/sources/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1eb 
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: verifyiface: package "genstatic" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference 
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: goanalysis_metalinter: verifyiface: package "genstatic" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference
```

</details>

So I will decline your PR, I recommend [creating a plugin](https://golangci-lint.run/contributing/new-linters/#how-to-add-a-private-linter-to-golangci-lint) with your linter.

**Pull request closed without merging**
