### PR TITLE
chore: upgrade tetrafro/godot linter

### PR DESCRIPTION
**Pull request by webstradev**
There was recently a new release of godot with some nice fixes which should be included in golangci-lint

### CODE REVIEW

**Comment by ldez** [comment]
The update of linter is done automatically by the dependabot: #4993

**Comment by webstradev** [comment]
> The update of linter is done automatically by the dependabot: #4993

Ah that makes a lot of sense actually, I couldn't really imagine that was done manually :).

Just out of curiosity what is the frequency of dependabot triggering new updates?

**Comment by ldez** [comment]
https://github.com/golangci/golangci-lint/blob/master/.github/dependabot.yml

**Comment by webstradev** [comment]
Excellent thank you!

**Pull request closed without merging**
