### PR TITLE
Printing out SuggestedFixes

### PR DESCRIPTION
**Pull request by SVilgelm**
output:
```
pkg/cmd/register/routes.go:40:12: fieldalignment: struct with 32 pointer bytes could be 16 (govet)
type route struct {
           ^
Rearrange fields
struct {
        HTTPMethods map[string]*httpMethod `json:"httpMethods"`
        Route       string                 `json:"route"`
        Streamable  bool                   `json:"isStreamable,omitempty"`
        AdminOnly   bool                   `json:"isAdminOnlyAccess,omitempty"`
        APIOnly     bool                   `json:"apiOnlyAccess,omitempty"`
}
```

### CODE REVIEW

**Comment by SVilgelm** [comment]
I still don't understand how to use the `SuggestedFixes` properly, but I want to print them out, at least.

**Comment by ldez** [comment]
I'm also working on :wink:

**Comment by ldez** [comment]
Maybe you can open an issue?

related to https://github.com/golangci/golangci-lint/issues/1322

**Comment by ldez** [comment]
I created an issue:  #1779

**Comment by SVilgelm** [comment]
@ldez 
actually I need this for `govet`, otherwise it's unclear what to do :))
I will keep it open for some time, then will close (when the autofix works)

**Comment by SVilgelm** [comment]
some screen shots:

Screen Shot 2021-02-25 at 1 59 01 PM
Screen Shot 2021-02-25 at 2 18 59 PM
Screen Shot 2021-02-25 at 2 21 10 PM


`nlreturn` removes the lines, that's why there are empty lines

**Pull request closed without merging**
