### PR TITLE
Enable auto-fixing when running via pre-commit

### PR DESCRIPTION
**Pull request by aneeshusa**
Thank you for the pull request!

Please make sure you didn't directly change `README.md`: it should be changed only by changing `README.tmpl.md` and running `make readme`.

### CODE REVIEW

**Comment by aneeshusa** [comment]
@diegs pointed out this great feature in v1.15.0 - we just updated everyone at our company to 1.16.0 and I'm super excited about `--fix`!

**Comment by jirfag** [comment]
thank you!
I'm not sure is it ok to merge now because old versions of golangci-lint without `--fix` support will fail. Maybe we should make another target like `golangci-lint-autofix`?

**Comment by aneeshusa** [comment]
That shouldn't be an issue as pre-commit will use the .pre-commit-hooks.yaml (in this repo) that exists in the golangci-lint version the user specifies in their .pre-commit-config.yaml. So, if they use an older version of golangci-lint, `--fix` won't be specified and it should work fine.

**Comment by jirfag** [comment]
ok, thank you

**Pull request merged**
