### PR TITLE
feat: add new whyvarscope linter

### PR DESCRIPTION
**Pull request by itsamirhn**
Hi,

I'd like to add a new linter: [whyvarscope](https://github.com/itsamirhn/whyvarscope)

It looks for variable scoped if statements and if the variable can be removed, it suggest to do that.

For example:
```go
if r := rand.Int(); r == 0 {
    println("Lucky")
}
```

Could be convert to:
```go
if rand.Int() == 0 {
    println("Lucky")
}
```

It also cares for some edge cases like and do not report error:
```go
if r1, r2 := multiReturnFunc(); r1 == r2 {
    println("Equal")
}
```

### CODE REVIEW

**Comment by ldez** [comment]
In order for a pull request adding a linter to be reviewed, the linter and the PR must follow some requirements.

- [ ] The CLA must be signed

### Pull Request Description

- [ ] It must have a link to the linter repository.
- [ ] It must provide a short description of the linter.

### Linter

- [ ] It must not be a duplicate of another linter or a rule of a linter. (the team will help to verify that)
- [ ] It must have a valid license (AGPL is not allowed) and the file must contain the required information by the license, ex: author, year, etc.
- [ ] The linter repository must have a CI and tests.
- [ ] It must use [`go/analysis`](https://golangci-lint.run/contributing/new-linters/).
- [ ] It must have a valid tag, ex: `v1.0.0`, `v0.1.0`.
- [ ] It must not contain `init()`.
- [ ] It must not contain `panic()`.
- [ ] It must not contain `log.fatal()`, `os.exit()`, or similar.
- [ ] It must not modify the AST.
- [ ] It must not have false positives/negatives. (the team will help to verify that)
- [ ] It must have tests inside golangci-lint.

### The Linter Tests Inside Golangci-lint

- [ ] They must have at least one std lib import.
- [ ] They must work with `T=<name of the linter test file>.go make test_linters`. (the team will help to verify that)

### `.golangci.next.reference.yml`

- [ ] The file `.golangci.next.reference.yml` must be updated.
- [ ] The file `.golangci.reference.yml` must NOT be edited.
- [ ] The linter must be added to the list of available linters (alphabetical case-insensitive order).
    - `enable` and `disable` options
- [ ] If the linter has a configuration, the exhaustive configuration of the linter must be added (alphabetical case-insensitive order)
    - The values must be different from the default ones.
    - The default values must be defined in a comment.
    - The option must have a short description.

### Others Requirements

- [ ] The files (tests and linter) inside golangci-lint must have the same name as the linter.
- [ ] The `.golangci.yml` of golangci-lint itself must not be edited and the linter must not be added to this file.
- [ ] The linters must be sorted in the alphabetical order (case-insensitive) in the `lintersdb/builder_linter.go` and `.golangci.next.reference.yml`.
- [ ] The load mode (`WithLoadMode(...)`):
    - if the linter doesn't use types: `goanalysis.LoadModeSyntax`
    - `goanalysis.LoadModeTypesInfo` required `WithLoadForGoAnalysis()` in the `lintersdb/builder_linter.go`
- [ ] The version in `WithSince(...)` must be the next minor version (`v1.X.0`) of golangci-lint.
- [ ] `WithURL()` must contain the URL of the repository.

### Recommendations

- [ ] The file `jsonschema/golangci.next.jsonschema.json` should be updated.
- [ ] The file `jsonschema/golangci.jsonschema.json` must NOT be edited.
- [ ] The linter repository should have a readme and linting.
- [ ] The linter should be published as a binary. (useful to diagnose bug origins)

---

The golangci-lint team will edit this comment to check the boxes before and during the review.

The code review will start after the completion of those checkboxes (except for the specific items that the team will help to verify).

If the author of the PR is a member of the golangci-lint team, he should not edit this message.

**This checklist does not imply that we will accept the linter.**

**Comment by Antonboom** [comment]
> Why var scope?

Sometimes this is useful for debug in IDE, especially if function result cannot be executed at breakpoint time.
JFYI

**Comment by ldez** [comment]
The reviews should be addressed as commits (no rebase, no push-force, except if there are conflicts)

**Comment by itsamirhn** [comment]
Oh my bad. I was bumping up my linter version.

**Comment by ldez** [comment]
As long as the elements required by the checklist (except those related to maintainer actions) are not handled, the review will not start.

**Comment by itsamirhn** [comment]
I'm sorry but i think I make the changes done (such as adding to the list of available linters or .gitignore) but it's still uncheck. What should i do?

**Comment by ldez** [comment]
> What should i do?

please read the checklist.

**Comment by ldez** [comment]
I'm not a bot.

**Comment by itsamirhn** [comment]
>  The linter must be added to the list of available linters (alphabetical case-insensitive order)

Is't already added and sorted?

**Comment by ldez** [comment]
The full quote:

> [ ] The linter must be added to the list of available linters (alphabetical case-insensitive order).
>   - `enable` and `disable` options

**Comment by ldez** [comment]
Although the items required by the checklist are still not addressed, I will provide a review.

The following examples are illustrations of what we may call false positives:

- error handling:
```go
func sample() {
	if err := operation(); err == nil {
		fmt.Println("foo")
	}
}
```

- multiple values:
```go
func sample(req *http.Request, a string) {
	if myHeader := req.Header.Get("My-Header"); myHeader == "" && a != "" {
		fmt.Println(a)
	}
}
```

- named boolean:
```go
func sample() {
	if isPreflight := operation(); isPreflight {
		fmt.Println("foo")
	}
}
```

All those cases are legit because the variables are used for readability.

IMO, this linter will lead to bad practices: readability is more important than removing a local variable that the compiler already removes during compilation.

So I will decline this linter.

You can still use it as a plugin: https://golangci-lint.run/contributing/new-linters/#how-to-add-a-private-linter-to-golangci-lint

**Comment by itsamirhn** [comment]
Thanks for your review.

**Pull request closed without merging**
