### PR TITLE
build(deps): bump github.com/GaijinEntertainment/go-exhaustruct/v3 from 2.3.0 to 3.1.0

### LINKED ISSUE #3960: Support exhaustruct v3
### Your feature request related to a problem? Please describe.

Exhaustruct has upgraded to v3 and new feature development will happen in this version

### Describe the solution you'd like.

golangci-lint should support exhaustruct v3

### Describe alternatives you've considered.

Stick to exhaustruct v2 features

### Additional context.

GaijinEntertainment/go-exhaustruct#67

### PR DESCRIPTION
**Pull request by ldez**
Bumps [github.com/GaijinEntertainment/go-exhaustruct/v3](https://github.com/GaijinEntertainment/go-exhaustruct) from 2.3.0 to 3.1.0.

https://github.com/GaijinEntertainment/go-exhaustruct/compare/v2.3.0...v3.1.0

https://github.com/GaijinEntertainment/go-exhaustruct/releases/tag/v3.0.0

Fixes #3960

**This update is done by hand because dependabot is not able to update a major version of a dependency.**

### CODE REVIEW

**Review by bombsimon — APPROVED** [review]
LGTM!

Let's remember to add a note in the next release notes that users may have to change their regex due to the breaking change in v3.

**Comment by orestisfl** [comment]
> LGTM!
> 
> Let's remember to add a note in the next release notes that users may have to change their regex due to the breaking change in v3.

@bombsimon I don't see this in the latest release notes. For reference, the breaking changes for exhaustruct: https://github.com/GaijinEntertainment/go-exhaustruct/releases/tag/v3.0.0

**Comment by ldez** [comment]
I will add a note in the next release.

**Comment by Nivl** [comment]
For reference this used to work before: `'sql\.NullString$'`, now it needs to be `'database/sql\.NullString$'`. For 3rd party packages you need to use the full package name like `'github.com/google/uuid\.NullUUID$'` instead of `'uuid\.NullUUID$'`

**Pull request merged**
