### PR TITLE
Add interfaceguard linter

### PR DESCRIPTION
**Pull request by jkeys089**
[interfaceguard](https://github.com/jkeys089/interfaceguard) finds subtle interface-related issues, including improper comparisons and type mismatches.

Example:

<details>

```go
package main

import "fmt"

type Greeter interface {
	SayHi() string
}

type CostcoGreeter struct {}

func (c *CostcoGreeter) SayHi() string {
	return "Welcome to Costco, I love you."
}

func main() {
	var greeter Greeter = getCachedCostcoGreeter()
	
	if greeter == nil {
		panic("greeter is nil") // we might expect this to panic, but it doesn't!
	}
	
	fmt.Println("ok")
}

func getCachedCostcoGreeter() *CostcoGreeter {
	return nil
}
```

</details>

This is a safer way to check if an interface is nil:

<details>

```go
package main

import (
	"fmt"
	"reflect"
)

type Greeter interface {
	SayHi() string
}

type CostcoGreeter struct {}

func (c *CostcoGreeter) SayHi() string {
	return "Welcome to Costco, I love you."
}

func main() {
	var greeter Greeter = getCachedCostcoGreeter()

	if isNil(greeter) {
		panic("greeter is nil") // now we catch the nil greeter and panic as expected
	}

	fmt.Println("ok")
}

func getCachedCostcoGreeter() *CostcoGreeter {
	return nil
}

func isNil(val any) bool {
	//nolint:interfaceguard
	if val == nil {
		return true
	}

	v := reflect.ValueOf(val)

	//nolint:exhaustive
	switch v.Kind() {
	case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer,
		reflect.UnsafePointer, reflect.Interface, reflect.Slice:
		return v.IsNil()
	default:
		return false
	}
}
```

</details>

What about comparing two interface values to each other:

<details>

```go
package main

import "fmt"

type Greeter interface {
	SayHi() string
}

type WallyWorldGreeter struct {}

func (w *WallyWorldGreeter) SayHi() string {
	return "Sorry, folks! We're closed for two weeks to clean and repair America's favorite family fun park. Sorry, uh-huh, uh-huh, uh-huh!"
}

func main() {
	var greeterA Greeter
	var greeterB Greeter = getCachedWallyWorldGreeter()
	
	if greeterA == greeterB {
		panic("greeterA == greeterB") // we might expect this to panic since both are nil, but it doesn't!
	}
	
	fmt.Println("ok")
}

func getCachedWallyWorldGreeter() *WallyWorldGreeter {
	return nil
}
```

Interface equality checks can be tricky! Here is a safer approach:
```go
package main

import (
	"fmt"
	"reflect"
)

type Greeter interface {
	SayHi() string
}

type WallyWorldGreeter struct {}

func (w *WallyWorldGreeter) SayHi() string {
	return "Sorry, folks! We're closed for two weeks to clean and repair America's favorite family fun park. Sorry, uh-huh, uh-huh, uh-huh!"
}

func main() {
	var greeterA Greeter
	var greeterB Greeter = getCachedWallyWorldGreeter()

	if isEqual(greeterA, greeterB) {
		panic("greeterA == greeterB") // now we see them as equal and panic as expected
	}
	
	fmt.Println("ok")
}

func getCachedWallyWorldGreeter() *WallyWorldGreeter {
	return nil
}

func isEqual(greeterA, greeterB Greeter) bool {
	if isNil(greeterA) && isNil(greeterB) {
		return true
	}
	
	return reflect.DeepEqual(greeterA, greeterB)
}

func isNil(val any) bool {
	//nolint:interfaceguard
	if val == nil {
		return true
	}

	v := reflect.ValueOf(val)

	//nolint:exhaustive
	switch v.Kind() {
	case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer,
		reflect.UnsafePointer, reflect.Interface, reflect.Slice:
		return v.IsNil()
	default:
		return false
	}
}
```

</details>

### CODE REVIEW

**Comment by ldez** [comment]
In order for a pull request adding a linter to be reviewed, the linter and the PR must follow some requirements.

- [ ] The CLA must be signed

### Pull Request Description

- [ ] It must have a link to the linter repository.
- [ ] It must provide a short description of the linter.

### Linter

- [ ] It must not be a duplicate of another linter or a rule of a linter (the team will help to verify that).
- [ ] It must have a valid license (AGPL is not allowed), and the file must contain the required information by the license, ex: author, year, etc.
- [ ] It must use Go version <= 1.21
- [ ] The linter repository must have a CI and tests.
- [ ] It must use [`go/analysis`](https://golangci-lint.run/contributing/new-linters/).
- [ ] It must have a valid tag, ex: `v1.0.0`, `v0.1.0`.
- [ ] It must not contain `init()`.
- [ ] It must not contain `panic()`.
- [ ] It must not contain `log.Fatal()`, `os.Exit()`, or similar.
- [ ] It must not modify the AST.
- [ ] It must not have false positives/negatives (the team will help to verify that).
- [ ] It must have tests inside golangci-lint.

### The Linter Tests Inside Golangci-lint

- [ ] They must have at least one std lib import.
- [ ] They must have integration tests without configuration (default).
- [ ] They must have integration tests with configuration (if the linter has a configuration).

### `.golangci.next.reference.yml`

- [ ] The file `.golangci.next.reference.yml` must be updated.
- [ ] The file `.golangci.reference.yml` must NOT be edited.
- [ ] The linter must be added to the lists of available linters (alphabetical case-insensitive order).
    - `enable` and `disable` options
- [ ] If the linter has a configuration, the exhaustive configuration of the linter must be added (alphabetical case-insensitive order)
    - The values must be different from the default ones.
    - The default values must be defined in a comment.
    - The option must have a short description.

### Others Requirements

- [ ] The files (tests and linter) inside golangci-lint must have the same name as the linter.
- [ ] The `.golangci.yml` of golangci-lint itself must not be edited and the linter must not be added to this file.
- [ ] The linters must be sorted in the alphabetical order (case-insensitive) in the `lintersdb/builder_linter.go` and `.golangci.next.reference.yml`.
- [ ] The load mode (`WithLoadMode(...)`):
    - if the linter uses `goanalysis.LoadModeSyntax` -> no `WithLoadForGoAnalysis()` in `lintersdb/builder_linter.go`
    - if the linter uses `goanalysis.LoadModeTypesInfo`, it requires `WithLoadForGoAnalysis()` in `lintersdb/builder_linter.go`
- [ ] The version in `WithSince(...)` must be the next minor version (`v1.X.0`) of golangci-lint.
- [ ] `WithURL()` must contain the URL of the repository.

### Recommendations

- [ ] The file `jsonschema/golangci.next.jsonschema.json` should be updated.
- [ ] The file `jsonschema/golangci.jsonschema.json` must NOT be edited.
- [ ] The linter repository should have a readme and linting.
- [ ] The linter should be published as a binary (useful to diagnose bug origins).
- [ ] The linter repository should have a `.gitignore` (IDE files, binaries, OS files, etc. should not be committed)
- [ ] A tag should never be recreated.
- [ ] use `main` as the default branch name.

---

The golangci-lint team will edit this comment to check the boxes before and during the review.

The code review will start after the completion of those checkboxes (except for the specific items that the team will help to verify).

The reviews should be addressed as commits (no squash).

If the author of the PR is a member of the golangci-lint team, he should not edit this message.

**This checklist does not imply that we will accept the linter.**

**Comment by Antonboom** [comment]
`staticcheck` uses complex "nilness" analyzer to detect such cases.

I am not sure that you implemented it correctly (the code looks quite simple at first glance).

Looks like covered by https://staticcheck.dev/docs/checks/:

- [SA4022](https://staticcheck.dev/docs/checks/#SA4022)	Comparing the address of a variable against nil
- [SA4023](https://staticcheck.dev/docs/checks/#SA4023)	Impossible comparison of interface value with untyped nil
- [SA4031](https://staticcheck.dev/docs/checks/#SA4031)	Checking never-nil value against nil
etc.

**Comment by ldez** [comment]
Duplicate of rules inside staticcheck.

**Comment by Antonboom** [comment]
> wasn’t reporting these issues

I just tried the first example from you repo:

```
/tmp                                                                                                                                                  
$ go install honnef.co/go/tools/cmd/staticcheck@2024.1.1

$ vim main.go
$ go run main.go
ok

$ staticcheck main.go
main.go:18:5: this comparison is never true (SA4023)
	main.go:16:24: the lhs of the comparison gets its value from here and has a concrete type
```

> what caused you to think it may not be implemented correctly?

At runtime time there are a lot of poinst when interfaces can be equal or not / safe to be compared/assignment or not (during to assignments to `nil`, or to narrower or wider interfaces, type casts. etc.). But you just uses simple assertions, that covers primitive cases only

```go
func isInterfaceType(typ types.Type) bool {
	_, ok := typ.Underlying().(*types.Interface)
	return ok
}

func isNil(expr ast.Expr) bool {
	ident, ok := expr.(*ast.Ident)
	return ok && ident.Name == "nil"
}
```

**Comment by jkeys089** [comment]
> > wasn’t reporting these issues
> 
> I just tried the first example from you repo:
> 
> ```
> /tmp                                                                                                                                                  
> $ go install honnef.co/go/tools/cmd/staticcheck@2024.1.1
> 
> $ vim main.go
> $ go run main.go
> ok
> 
> $ staticcheck main.go
> main.go:18:5: this comparison is never true (SA4023)
> 	main.go:16:24: the lhs of the comparison gets its value from here and has a concrete type
> ```

_Golangci-lint_ isn’t reporting these for me (almost certainly because of some issue with my configuration - I’ll spend time to verify this week).

> 
>  > what caused you to think it may not be implemented correctly?
> 
> At runtime time there are a lot of points when interfaces can be equal or not / safe to be compared/assignment or not (during to assignments to `nil`, or to narrower or wider interfaces, type casts. etc.). But you use simple assertions, that covers primitive "static" cases only
> 
> ```go
> func isInterfaceType(typ types.Type) bool {
> 	_, ok := typ.Underlying().(*types.Interface)
> 	return ok
> }
> 
> func isNil(expr ast.Expr) bool {
> 	ident, ok := expr.(*ast.Ident)
> 	return ok && ident.Name == "nil"
> }
> ```

Thanks for the feedback! I spent a bit of time writing tests to be sure I found all kinds of different cases I could think of but it is certainly possible I’ve missed more complex / nuanced scenarios. I’ll look more closely at some other linters for inspiration.

**Comment by jkeys089** [comment]
@Antonboom I looked into it more this morning and I'm still unable to get `golangci-lint` to find these issues on a real codebase. I also tried running the `staticcheck` binary directly on the same codebase and it didn't report any issues either. However, `interfaceguard` is correctly reporting the issue. I updated the examples in the `interfaceguard` README to better represent the kind of issues I've recently seen in real codebases that slipped past `golangci-lint`.

Example `main.go`:
```go
package main

import (
	"fmt"
	"time"
)

type Greeter interface {
	SayHi() string
}

type CostcoGreeter struct {}

func (c *CostcoGreeter) SayHi() string {
	return "Welcome to Costco, I love you."
}

func main() {
	var greeter Greeter = getCachedGreeter()
	
	if greeter == nil {
		panic("greeter is nil") // we might expect this to panic, but it doesn't!
	}
	
	fmt.Println("ok")
}

// getCachedGreeter simulates cache miss at runtime and will always return nil *CostcoGreeter
func getCachedGreeter() Greeter {
	now := time.Now().Unix()

	switch {
	case now == 0:
		return new(CostcoGreeter)
	case now == 1:
		return nil
	default:
		var c *CostcoGreeter
		return c
	}
}
```

```shell
go install honnef.co/go/tools/cmd/staticcheck@2024.1.1

# below finds nothing
staticcheck main.go
```

Do you have any thoughts on proceeding with this PR vs attempting to contribute some improvements to `staticcheck` directly?

**Comment by jkeys089** [comment]
@Antonboom @ldez I [checked in with the staticcheck project](https://github.com/dominikh/go-tools/issues/1596) and they acknowledged `staticcheck` will not detect the same types of issues as `interfaceguard`. However, they do not believe the checks performed by `interfaceguard` would be a good fit directly within that project. In other words, `interfaceguard` is different from `staticcheck` and they have opted not to include the new checks from `interfaceguard` directly in `staticcheck`.

The `staticcheck` project appears to be a bit more strict about what should _certainly_ be considered a bug vs _potentially_ a bug. I agree the types of issues being reported by `interfaceguard` are more subtle / nuanced and some may not consider them to be outright bugs. However, we ran into a very real bug caused by this issue and then used `interfaceguard` to find several more instances in our projects. So, I believe it is still valuable to consider.

Please let me know if you might reconsider including `interfaceguard` as an optional linter now that we know it is not duplicating `staticcheck` rules. Thanks!

**Comment by ldez** [comment]
> The staticcheck project appears to be a bit more strict about what should certainly be considered a bug vs potentially a bug.

We follow basically the same rule: potential error "detectors" are not accepted.

**Comment by jkeys089** [comment]
> We follow basically the same rule: potential error "detectors" are not accepted.
> 
> You can show that is the first message:
> 
> > [ ] It must not have false positives/negatives (the team will help to verify that).

Got it. With this understanding, I have just one last question before I give up: would it be possibly be more appropriate to classify this under the "style" preset as opposed to "bugs"? I can see how it might be considered a project-by-project stylistic choice to prohibit direct interface comparisons rather than considering it a bug.

I'm more than willing to accept I might be the only person who benefits from this type of check 😄 but I'd hate to give up if this could potentially benefit others.

Thanks again for taking time to respond.

**Comment by ldez** [comment]
> would it be possibly be more appropriate to classify this under the "style" preset as opposed to "bugs"?

Not really, because it's not what we can call "style".

In all cases, for now, "detectors" are not accepted, you are not the first person who proposes this type of element.

An example of a refused "detector" is [nilaway](https://github.com/uber-go/nilaway), and we have refused it for the same reason as yours.

It's a no but it's a no for now.
Maybe in the future, we will reevaluate this need (for "detectors") and how to handle it.

Thank you for your positive and constructive reaction, it is appreciated.

**Pull request closed without merging**
