### PR TITLE
docs: update completion guide

### PR DESCRIPTION
**Pull request by alexandear**
This PR updates "Shell Completion" guide.

### CODE REVIEW

**Comment by ldez** [comment]
The current sentences are a note about a limitation with Bash, this is not Bash section, we will not describe each completion possibility (and only on macOS) it makes no sense.

**Comment by alexandear** [comment]
So, maybe we can delete `Linux` section also? And leave only:

---
## Shell Completion

`golangci-lint` can generate Bash, fish, PowerShell, and Zsh completion files.

See the instructions on `golangci-lint completion <YOUR_SHELL> --help` (replace `<YOUR_SHELL>` with your favorite one).

### macOS

There are two versions of `bash-completion`, v1 and v2. V1 is for Bash 3.2 (which is the default on macOS), and v2 is for Bash 4.1+. The `golangci-lint` completion script doesn’t work correctly with bash-completion v1 and Bash 3.2. It requires bash-completion v2 and Bash 4.1+. Thus, to be able to correctly use `golangci-lint` completion on macOS, you have to install and use Bash 4.1+ ([instructions](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba)). The following instructions assume that you use Bash 4.1+ (that is, any Bash version of 4.1 or newer).

Install `bash-completion v2`:

```bash
brew install bash-completion@2
echo 'export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"' >>~/.bashrc
echo '[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"' >>~/.bashrc
exec bash # reload and replace (if it was updated) shell
type _init_completion && echo "completion is OK" # verify that bash-completion v2 is correctly installed
```

Add `golangci-lint` bash completion:

```bash
echo 'source <(golangci-lint completion bash)' >>~/.bashrc
source ~/.bashrc
```

**Comment by ldez** [comment]
It's a better idea.

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
