### PR TITLE
docs: add more tagliatelle examples

### PR DESCRIPTION
**Pull request by pershin-daniil**
Sync settings here and in https://github.com/ldez/tagliatelle?tab=readme-ov-file#as-a-golangci-lint-linter

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

The goal is not to be exhaustive because you can define all the tag names you want.

This is just an example.

**Comment by pershin-daniil** [comment]
I've just came up with an issue that there is no info about `toml` in `golangci` docs but it is in readme.md. It is confusing.

Is there any place with all tags or with all possible settings?

**Comment by ldez** [comment]
> Is there any place with all tags or with all possible settings?

It's impossible to do because everybody can create a custom tag name and new "official" tag names can appear.

The only setting with a limited set of values is the case.

**Comment by ldez** [comment]
We can add the `toml` example but the exhaustivity is impossible, the tagliatelle doc and golangci-lint doc don't need to be synced.

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
