### PR TITLE
add containedctx linter

### PR DESCRIPTION
**Pull request by sivchari**
containedctx is a linter that detects struct contained context.Context field
in detail, please check following link.
https://github.com/sivchari/containedctx

### CODE REVIEW

**Comment by Antonboom** [comment]
@sivchari, FYI – it's OK pass `Context` in the struct for tracing purpose.

For example:
```go
result := client.ExternalServiceCall()
span, ctx := tracer.ExtractSpan(result.Ctx)
// Deal with external service span.
```

**Comment by sivchari** [comment]
[context](https://pkg.go.dev/context)

> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx

Your example code depends on package design of 3rd library.
And, this linter don't detect external code.
Additional, if you wanna to contain context.Context in struct, you can disable this linter.

**Comment by Antonboom** [comment]
@sivchari I'm familiar with context doc :)
Yes, you can blame the third-party library, but it's hard to argue with it when it is the de facto standard.

I have nothing against linter. It was just notification for u, that not everything is so simple.

**Comment by sivchari** [comment]
I'm not sure which library you mean by de facto standard, but Many third-library declared interface to pass context to first parameter.
The third-library for using data tracing (e.g. dogstatsd, prometheus API ) shod be pass the first parameter too.
However, it's also true, as you say, that some third libraries contain context.Context in struct.
But Go team recommends not to contain context.Context in struct, so this linter is meant to keep it that way.
Thanks for comment.

**Comment by bombsimon** [comment]
> But Go team recommends not to contain context.Context in struct, so this linter is meant to keep it that way.

Do you have a reference for that? I think it's pretty common when you implement servers or clients to have some base context, contexts with timeouts or contexts with cancellation on a struct that implements either of these.

I generally don't think `golangci-lint` should be opinionated and decide what's useful or not, it's just new to me that this would be a bad pattern.

**Comment by ldez** [comment]
@bombsimon https://pkg.go.dev/context

> think it's pretty common when you implement servers or clients to have some base context, contexts with timeouts or contexts with cancellation on a struct that implements either of these.

this is a bad practice :scream_cat:

**Comment by bombsimon** [comment]
> @bombsimon https://pkg.go.dev/context
> 
> > think it's pretty common when you implement servers or clients to have some base context, contexts with timeouts or contexts with cancellation on a struct that implements either of these.
> 
> this is a bad practice 🙀

Thanks! I just think I've never interpreted the text and example from the docs as spanning over _any_ struct. The example in the docs that says

> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx:

I think is referring to the receiving value in `DoSomething` which I totally get is bad practice. What I was more thinking about would be an implementation of some kind of protocol that passes a `ctx` to each handler, just like [the context that is stored on each `http.Request`](https://cs.opensource.google/go/go/+/refs/tags/go1.17.3:src/net/http/request.go;l=319-323;drc=refs%2Ftags%2Fgo1.17.3) in stdlib.

But I guess there's no way to tell how the struct is used and since a lot of code bases doesn't implement this kind of behavior I can see the use case for the linter.

**Comment by ldez** [comment]
`http.Request` is the exception that confirms the rule :wink:

**Comment by sivchari** [comment]
> Do you have a reference for that? 

Sorry, this is an interpretation with my own opinions. However, as the Go team commented as `The Context should be the first parameter, typically named ctx` comments, this pattern is bad.

FYI
https://go.dev/blog/context-and-structs

> Exception to the rule: preserving backwards compatibility

https://github.com/golang/go/blob/ecf6b52b7f4ba6e8c98f25adf9e83773fe908829/src/net/http/request.go#L319-L323

```go
	// ctx is either the client or server context. It should only
	// be modified via copying the whole Request using WithContext.
	// It is unexported to prevent people from using Context wrong
	// and mutating the contexts held by callers of the same request.
	ctx context.Context
```

The reason it is included in net/http is for backward compatibility reasons.

**Comment by bombsimon** [comment]
> `http.Request` is the exception that confirms the rule 😉
> 
> https://go.dev/blog/context-and-structs
>
> >  When designing an API with context, remember the advice: pass context.Context in as an argument; don’t store it in structs.

Heh, yeah usually that's the case with stdlib. 😄 But the gRPC example is a better example regarding what I meant with server implementation. It passes `context.Context` as an argument to each handler implementing a server but for internals it uses the struct to store it.

Another example where I don't see a problem storing it on structs would be in table driven testing.

```go
cases := []struct{
    description string
    path string
    ctx context.Context
}{
    {
      description: "Test foo",
      path:        "/foo/bar",
      ctx:          context.WithValue(context.Background(), someVal, "some-value")),
    },
}
```

Not saying this linter isn't good and obviously you provided links with more in depth information about this, thanks! I didn't know this was so generic.

So to clarify, I'm not talking about how contexts are passed to different methods or packages, I'm talking about contexts used to keep track of state in internal implementations.

**Comment by sivchari** [comment]
Back to the linter. I'm improving that.
Because, in the current function, the linter detects test case (e.g. table-driven-test).
table-driven-test is general and context is sometime contained in struct too.
So I'm improving to exclude test file.

**Comment by bombsimon** [comment]
> Back to the linter. I'm improving that. Because, in the current function, the linter detects test case (e.g. table-driven-test). table-driven-test is general and context is sometime contained in struct too. So I'm improving to exclude test file.

You don't have to do that in your linter for `golangci-lint` though, generally skipping tests in `golangci-lint` is handled with the implementation of that feature in `golangci-lint` itself. I'm also not sure skipping whole test files is the right way to go, I can see use cases of wanting to use this linter on test files as well.

**Comment by sivchari** [comment]
> You don't have to do that in your linter for golangci-lint though, generally skipping tests in golangci-lint is handled with the implementation of that feature in golangci-lint itself. I'm also not sure skipping whole test files is the right way to go, I can see use cases of wanting to use this linter on test files as well.

Oh, I've mistook. 
Thanks !

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
