### PR TITLE
Update to latest securego/gosec

### PR DESCRIPTION
**Pull request by rung**
### What
- Update gosec to use latest gosec
- Disable G307(`Deferring a method which returns an error`) because `errcheck` also has this rule.

### CODE REVIEW

**Comment by lopezator** [comment]
Hello, thanks for your contribution!

I need more info in order to approve this. 

Can you provide a code snippet where `errcheck` and `gosec` errors overlap?

**Comment by rung** [comment]
@lopezator @ernado Sorry for my late reply.
Because of world-wide chaos situation, I don't have a time to confirm it.

If it's good to close this PR for now, let me close this once. 🙇

**Comment by ernado** [comment]
Thank you anyway.

We will eventually update gosec, I'll try to find this example by myself.

**Comment by obl823** [comment]
What are you talkin about sir I did not pull any requests I believe you have the wrong individuals email

Sent from Yahoo Mail on Android 
 
  On Tue, Apr 21, 2020 at 8:49 PM, Aleksandr Razumov<notifications@github.com> wrote:   


Thank you anyway.

We will eventually update gosec, I'll try to find this example by myself.

**Pull request merged**
