### PR TITLE
docs: Update documentation and assets

### PR DESCRIPTION
**Pull request by golangci-releaser**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by ldez** [comment]
> @jirfag Could you please sing CLA for the @golangci-releaser bot? @ernado please ping @jirfag one more time

https://github.com/golangci/golangci-lint/pull/1872#issuecomment-819925452

**Comment by ldez** [comment]
This time we will not wait, I will create another PR.

**Review by saschagrunert — DISMISSED** [review]
LGTM

**Comment by ldez** [comment]
I close the old PR and keep only the latest. We still hope that @jirfag will fix the problem.

**Pull request closed without merging**
