### PR TITLE
 Added "bodyclose" support

### PR DESCRIPTION
**Pull request by gsora**
This commit adds full support for bodyclose linter
(https://github.com/timakin/bodyclose), which checks if an `http.Body`
element is correctly closed after usage.

Since it can be used via `go/analysis`, I followed the `govet` example
as suggested by https://github.com/golangci/golangci-lint/wiki/How-to-add-a-custom-linter.

This commit is fully tested, and contains a (flawed) test program which
calls `http.Get()` on `https://google.com` and does not closes its
corresponding `http.Body`.

### CODE REVIEW

**Comment by gsora** [comment]
Uhm, I do run `goimports` through VSCode on save, I don't understand why those errors appear.

**Comment by alexkohler** [comment]
@gsora - Perhaps you're using an older version of goimports? It could possibly be the import order. Typically I think goimports does standard library imports first.

**Comment by gsora** [comment]
I checked and I'm using the latest version of `golang.org/x/tools/cmd/goimports`, which seems to be used by `https://github.com/golangci/gofmt/blob/master/goimports/golangci.go` too.

**Comment by jirfag** [comment]
thank you for this contribution! it has some issues and I will fix them myself because it's my fault that it's being merged too long

**Pull request merged**
