### PR TITLE
dev: remove kortschak from generated team

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

### CODE REVIEW

**Comment by ldez** [comment]
Would you like to provide some explanation? You are not forced, it's just a question to understand your decision.

**Comment by kortschak** [comment]
Differences in opinion about approaches to linting at scale.

**Review by ldez — APPROVED** [review]

**Comment by kortschak** [comment]
Please also remove my avatar from https://contributors-img.web.app/image?repo=golangci/golangci-lint.

**Comment by ldez** [comment]
The image is based on GitHub contributors, we don't have a way to change this.

**Pull request merged**
