### PR TITLE
Show deprecated mark in the CLI linters help

### PR DESCRIPTION
**Pull request by Danil42Russia**
### Idea
Show deprecated mark in linter lists

#### Before:
`golint: Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes [fast: false, auto-fix: false]`

#### After:
`golint (deprecated): Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes [fast: false, auto-fix: false]`

#### Possible problems
It is possible that the deprecated mark is in the wrong place, but this can be changed :)

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

I'm thinking about the fact to use parentheses because we already use parentheses in the linter descriptions to display aliases, it can be confusing.

**Comment by SVilgelm** [comment]
lets use square brackets, but I think it will be great if we can highlight it by using red color:

Screen Shot 2021-11-13 at 1 01 05 PM

in this case all deprecated linters are visible.

Here is a diff:
```diff
diff --git a/pkg/commands/help.go b/pkg/commands/help.go
index f882d7c8..66ff5784 100644
--- a/pkg/commands/help.go
+++ b/pkg/commands/help.go
@@ -54,7 +54,7 @@ func printLinterConfigs(lcs []*linter.Config) {
                }
 
                if lc.IsDeprecated() {
-                       altNamesStr += " (deprecated)"
+                       altNamesStr += " [" + color.RedString("deprecated") + "]"
                }
 
                fmt.Fprintf(logutils.StdOut, "%s%s: %s [fast: %t, auto-fix: %t]\n", color.YellowString(lc.Name()),
```

**Comment by Danil42Russia** [comment]
@ldez, i completely agree that parentheses `()` in the proposed format are not convenient.

@SVilgelm suggested to use square brackets `[]` and put in color - i agree with this

But if you present this description:
```
super_linter (alias_super_linter_first, alias_super_linter_second) [deprecated]: type description of the super linter [fast: false, auto-fix: false]
```
then, the deprecated mark can be overlooked

Maybe move the deprecated mark to the very beginning?
```diff
+++		deprecatedMark := ""
		if lc.IsDeprecated() {
---			altNamesStr += " (deprecated)"
+++			deprecatedMark = "[" + color.RedString("deprecatedMark") + "] "
		}

---		fmt.Fprintf(logutils.StdOut, "%s%s: %s [fast: %t, auto-fix: %t]\n", color.YellowString(lc.Name()),
+++		fmt.Fprintf(logutils.StdOut, "%s%s%s: %s [fast: %t, auto-fix: %t]\n", deprecatedMark, color.YellowString(lc.Name()),
			altNamesStr, linterDescription, !lc.IsSlowLinter(), lc.CanAutoFix)
```

image

**Comment by ldez** [comment]
I think that the suggestion of @SVilgelm is enough to get the right visibility.
When you run golangci-lint with deprecated linters, you already have a log to inform about deprecation.

**Comment by Danil42Russia** [comment]
@ldez, made the changes that @Vilgelm suggested

**Review by SVilgelm — APPROVED** [review]

**Pull request merged**
