### PR TITLE
dev: reformat code with gofumpt

### PR DESCRIPTION
**Pull request by alexandear**
The PR reformats code with `gofumpt` linter.

### CODE REVIEW

**Comment by ldez** [comment]
can you rebase you PR?

**Comment by alexandear** [comment]
rebased

**Comment by ldez** [comment]
Because this configuration is used as a regression test I prefer to keep go fmt.
It allows us to follow the Go modification.

**Comment by alexandear** [comment]
Reverted changes for `.golangci.yml`, and changed accordingly PR's title and description.

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
