### PR TITLE
Add sleuth linter

### PR DESCRIPTION
**Pull request by sivchari**
sleuth is a tool that can detect when you have `length` and you `append`.
https://github.com/sivchari/sleuth

e.g.
```go
testdata := []int{1, 2, 3, 4, 5}

t1 := make([]int, 5)
for _, tt := range testdata {
	t1 = append(t1, tt) // ERROR "sleuth detects illegal"
}

t2 := make([]int, 0, 5)
for _, tt := range testdata {
	t2 = append(t2, tt) // OK
}
```

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

Currently, I'm not sure about the goal of this linter, the bug/problem solved by this linter is not clear for me.

I opened 2 issues (https://github.com/sivchari/sleuth/pull/7, https://github.com/sivchari/sleuth/pull/8) and 1 PR (https://github.com/sivchari/sleuth/pull/6) on the linter repo.

**Comment by sivchari** [comment]
Thanks for review. 
I've improved somethings you reviews.
Please review.

**Review by ldez — CHANGES_REQUESTED** [review]

**Comment by sivchari** [comment]
I am sorry for the many inconveniences I have caused.
Thank you very much.

**Comment by ashanbrown** [comment]
Does this do the same origin things as https://github.com/ashanbrown/makezero?

**Comment by ldez** [comment]
@ashanbrown you are right, because of the name `makezero` I was focus on the init part.

So we will decline this linter because it's a duplicate of `makezero`.

@sivchari even if your linter has not been accepted, hope it has been a good experience for you and you learn some new things.

**Comment by ashanbrown** [comment]
@sivchari if there are improvements this offers over makezero, we could consider switching.  I don't have time now but I'd like to compare them in more detail.

**Comment by sivchari** [comment]
@ashanbrown 
thx for comment me. ok, I waited your response :)

@ldez 
I've done good experiences and this experience has made me want to build a better linter!
thank you so much !!

**Pull request closed without merging**
