### PR TITLE
docs: add Drone Plugin for CI installation

### PR DESCRIPTION
**Pull request by oxr463**
See: https://github.com/rancherlabs/drone-plugin-golangci-lint

### CODE REVIEW

**Comment by ldez** [comment]
The CLA is still not signed after 5 months so I close the PR.

**Comment by oxr463** [comment]
> The CLA is still not signed after 5 months so I close the PR.

I did sign it. Not sure why it never updated. Can you please re-open this?

**Comment by ldez** [comment]
Can you click on the "recheck" https://github.com/golangci/golangci-lint/pull/2844#issuecomment-1124466629

**Comment by oxr463** [comment]
> Can you click on the "recheck" [#2844 (comment)](https://github.com/golangci/golangci-lint/pull/2844#issuecomment-1124466629)

Done.

**Pull request closed without merging**
