### PR TITLE
depguard: add current module name to allow list

### PR DESCRIPTION
**Pull request by mirecl**
**AS-IS**: `depguard/v2` automatic add current module name (from go.mod) in deny list.
**TO-BE**: `depguard/v2` automatic add current module name (from go.mod) in allow list.

### CODE REVIEW

**Comment by mirecl** [comment]
@alexandear, i'm sure this will be a useful addition, what do you think?

**Comment by ldez** [comment]
Hello,

I think it will create confusion: it's better to let the user create it's own configuration.
Also, the way to get the go.mod is too naive and it will not work in some context.

I will decline this PR.

**Comment by mirecl** [comment]
@ldez, your logic is strange, all will continue to do this setting, add current module to allow list!

**Comment by ldez** [comment]
An example of a real configuration:

```yml
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
```

As you can see the current module doesn't need to be added.

**Comment by mirecl** [comment]
But if you add at least 1 rule to the allowed list, then the current module becomes prohibited.

**Comment by ldez** [comment]
Yes because it's the way that depguard v2 works.

**Pull request closed without merging**
