### PR TITLE
feat: change err to nil

### PR DESCRIPTION
**Pull request by sashamelentyev**

### CODE REVIEW

**Comment by ldez** [comment]
Without any description, it's not possible to understand.

But the error of the walk needs to be returned.

**Comment by sashamelentyev** [comment]
@ldez, all code looks like this:
```go
func dirSizeBytes(path string) (int64, error) {
	var size int64
	err := filepath.Walk(path, func(_ string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			size += info.Size()
		}
		return nil
	})
	return size, err
}
```
we check err in first step, don't need return err in last line in filepath.Walk

**Comment by kamilsk** [comment]
`feat:` is incorrect here. I suggest avoiding a prefix or using`fix:`/`refactor:`

https://www.conventionalcommits.org/en/v1.0.0/

**Comment by kamilsk** [comment]
```go
		if err != nil {
			return err
		}
		if !info.IsDir() {
			size += info.Size()
		}
		return err
```

and

```go
		if err != nil {
			return err
		}
		if !info.IsDir() {
			size += info.Size()
		}
		return nil
```

are both unclear, but the second is just "optimization" of the first, nothing else

```go
		if err == nil && !info.IsDir() {
			size += info.Size()
		}
		return err
```

looks the same but holds

> the error of the walk needs to be returned

and reduces code lines

**Comment by kamilsk** [comment]
https://github.com/golangci/golangci-lint/pull/2970#issuecomment-1179761123

I'm talking about the commit message

image

**Comment by sashamelentyev** [comment]
@kamilsk i rename commit, but pr is closed

**Pull request closed without merging**
