### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by ccoVeille**
- chore: fix typo
- chore: fix registered trademarks
- chore: fix acronyms case
- chore: fix style

### CODE REVIEW

**Comment by ccoVeille** [comment]
I split PR in multiple commits to make things clearer, and allow me to prune/edit any commit you would like me to update/nuke

Feel free to squash them later

**Comment by ldez** [comment]
FYI, during a review, changes should be addressed as commits to ease the review.
You should never "edit" an existing commit to address review.

The PRs are always squashed during the merge of the PR, not inside the PR, to keep the history of the changes.

**Comment by ccoVeille** [comment]
> FYI, during a review, changes should be addressed as commits to ease the review. You should never "edit" an existing commit to address review.
> 
> The PRs are always squashed during the merge of the PR, not inside the PR, to keep the history of the changes.

OK, noted

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
