### PR TITLE
fix: wrong load mode

### LINKED ISSUE #1515: Can't run linter exportloopref
It doesn't seem to be possible to run `exportloopref` by itself, even on the simplest of packages. For example, this single file that imports `fmt` can't be analyzed:

```go
package main

import "fmt"

func main() {
	fmt.Println("hello")
}
```

```console
$ golangci-lint run --no-config --disable-all --enable exportloopref
WARN [runner] Can't run linter exportloopref: inspect: analysis skipped: errors in package: [/Users/cbandy/tmp/go/main.go:3:8: could not import fmt (Config.Importer.Import(fmt) returned nil but no error)]
ERRO Running error: inspect: analysis skipped: errors in package: [/Users/cbandy/tmp/go/main.go:3:8: could not import fmt (Config.Importer.Import(fmt) returned nil but no error)]
```

```console
$ golangci-lint run --no-config --disable-all --enable exportloopref --verbose
INFO [lintersdb] Active 1 linters: [exportloopref]
INFO [loader] Go packages loading at mode 7 (compiled_files|files|name) took 322.614921ms
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 1.58944ms
INFO [linters context/goanalysis] analyzers took 66.964µs with top 10 stages: exportloopref: 45.094µs, inspect: 21.87µs
WARN [runner] Can't run linter exportloopref: inspect: analysis skipped: errors in package: [/Users/cbandy/tmp/go/main.go:3:8: could not import fmt (Config.Importer.Import(fmt) returned nil but no error)]
INFO [runner] processing took 8.453µs with stages: nolint: 2.748µs, max_same_issues: 2.44µs, cgo: 431ns, skip_dirs: 409ns, path_prettifier: 350ns, autogenerated_exclude: 306ns, path_prefixer: 291ns, filename_unadjuster: 260ns, max_from_linter: 203ns, skip_files: 148ns, uniq_by_line: 137ns, diff: 137ns, identifier_marker: 131ns, sort_results: 73ns, max_per_file_from_linter: 68ns, source_code: 67ns, exclude: 67ns, path_shortener: 66ns, exclude-rules: 61ns, severity-rules: 60ns
INFO [runner] linters took 2.534605ms with stages: exportloopref: 2.482917ms
ERRO Running error: inspect: analysis skipped: errors in package: [/Users/cbandy/tmp/go/main.go:3:8: could not import fmt (Config.Importer.Import(fmt) returned nil but no error)]
INFO Memory: 6 samples, avg is 71.6MB, max is 71.6MB
INFO Execution took 405.393236ms
```

I've tried the latest release and built from `@master`.

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
golangci-lint has version 1.32.2 built from 52d26a3 on 2020-11-03T01:15:38Z
```
and
```
golangci-lint has version v1.32.3-0.20201117214611-c68692e99f34 built from (unknown, mod sum: "h1:TwcnmNXfBsx0UdOb3BaF0B2PYYdtEV11+Ad1qP1xMD4=") on (unknown)
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
cat: .golangci.yml: No such file or directory
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
go version go1.15.3 darwin/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cbandy/Library/Caches/go-build"
GOENV="/Users/cbandy/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/cbandy/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/cbandy/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/cbandy/.local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/cbandy/.local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/cbandy/tmp/go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bw/_dxdzsmx6h1ffcgp6rvfh55c0000gn/T/go-build901332976=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

<details><summary>Verbose output of running</summary>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
INFO [config_reader] Config search paths: [./ /Users/cbandy/tmp/go /Users/cbandy/tmp /Users/cbandy /Users /]
INFO [lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]
INFO [loader] Go packages loading at mode 575 (deps|exports_file|files|imports|name|compiled_files|types_sizes) took 289.052724ms
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 191.856µs
INFO [linters context/goanalysis] analyzers took 974.81474ms with top 10 stages: buildir: 705.474977ms, fact_purity: 86.725757ms, ctrlflow: 55.909102ms, inspect: 46.534415ms, printf: 44.046748ms, fact_deprecated: 34.00492ms, S1030: 131.503µs, ineffassign: 100.069µs, SA4021: 93.871µs, isgenerated: 89.483µs
INFO [linters context/goanalysis] analyzers took 2.766319ms with top 10 stages: buildir: 2.605689ms, U1000: 160.63µs
INFO [runner] processing took 7.439µs with stages: max_same_issues: 2.608µs, nolint: 1.929µs, skip_dirs: 374ns, cgo: 275ns, max_from_linter: 271ns, path_prettifier: 270ns, skip_files: 218ns, filename_unadjuster: 179ns, path_prefixer: 172ns, autogenerated_exclude: 168ns, uniq_by_line: 151ns, diff: 146ns, identifier_marker: 145ns, path_shortener: 80ns, source_code: 80ns, max_per_file_from_linter: 78ns, sort_results: 77ns, exclude: 75ns, exclude-rules: 73ns, severity-rules: 70ns
INFO [runner] linters took 2.138641413s with stages: goanalysis_metalinter: 2.101323097s, unused: 37.254885ms
INFO File cache stats: 0 entries of total size 0B
INFO Memory: 26 samples, avg is 150.1MB, max is 207.4MB
INFO Execution took 2.441623457s
```

</details>

### PR DESCRIPTION
**Pull request by ldez**
Fixes #1515

I tested all the linters.

To avoid that in the future, every testdata for a linter must contain at least one import.

Before the fix:

```console
$ go run ./cmd/golangci-lint/ run --no-config --disable-all --enable=asciicheck ./test/testdata/depguard.go 
WARN [runner] Can't run linter asciicheck: asciicheck: analysis skipped: errors in package: [/home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:6:2: could not import compress/gzip (Config.Importer.Import(compress/gzip) returned nil but no error) /home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:7:2: could not import log (Config.Importer.Import(log) returned nil but no error)] 
ERRO Running error: asciicheck: analysis skipped: errors in package: [/home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:6:2: could not import compress/gzip (Config.Importer.Import(compress/gzip) returned nil but no error) /home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:7:2: could not import log (Config.Importer.Import(log) returned nil but no error)] 
exit status 3
```

```console
$ go run ./cmd/golangci-lint/ run --no-config --disable-all --enable=exhaustivestruct ./test/testdata/depguard.go
WARN [runner] Can't run linter exhaustivestruct: inspect: analysis skipped: errors in package: [/home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:6:2: could not import compress/gzip (Config.Importer.Import(compress/gzip) returned nil but no error) /home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:7:2: could not import log (Config.Importer.Import(log) returned nil but no error)] 
ERRO Running error: inspect: analysis skipped: errors in package: [/home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:6:2: could not import compress/gzip (Config.Importer.Import(compress/gzip) returned nil but no error) /home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:7:2: could not import log (Config.Importer.Import(log) returned nil but no error)] 
exit status 3
```

```console
$ go run ./cmd/golangci-lint/ run --no-config --disable-all --enable=exportloopref ./test/testdata/depguard.go
WARN [runner] Can't run linter exportloopref: inspect: analysis skipped: errors in package: [/home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:6:2: could not import compress/gzip (Config.Importer.Import(compress/gzip) returned nil but no error) /home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:7:2: could not import log (Config.Importer.Import(log) returned nil but no error)] 
ERRO Running error: inspect: analysis skipped: errors in package: [/home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:6:2: could not import compress/gzip (Config.Importer.Import(compress/gzip) returned nil but no error) /home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:7:2: could not import log (Config.Importer.Import(log) returned nil but no error)] 
exit status 3
```

```console
$ go run ./cmd/golangci-lint/ run --no-config --disable-all --enable=makezero ./test/testdata/depguard.go
WARN [runner] Can't run linter makezero: makezero: analysis skipped: errors in package: [/home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:6:2: could not import compress/gzip (Config.Importer.Import(compress/gzip) returned nil but no error) /home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:7:2: could not import log (Config.Importer.Import(log) returned nil but no error)] 
ERRO Running error: makezero: analysis skipped: errors in package: [/home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:6:2: could not import compress/gzip (Config.Importer.Import(compress/gzip) returned nil but no error) /home/ldez/sources/go/src/github.com/golangci/golangci-lint/test/testdata/depguard.go:7:2: could not import log (Config.Importer.Import(log) returned nil but no error)] 
exit status 3
```

### CODE REVIEW

**Comment by cbandy** [comment]
Did adding the `import` statements cause existing tests to fail?

**Comment by ldez** [comment]
Without my fix, those tests fail with an import.

**Review by cbandy — COMMENTED** [review]
Excellent!

**Comment by SVilgelm** [comment]
It's weird, but it works, I just tested on master and with this changes.

**Review by SVilgelm — APPROVED** [review]
Looks good to me. Thank you

**Pull request merged**
