### PR TITLE
Add errcheck option WithoutTests

### PR DESCRIPTION
**Pull request by grongor**
I'm sorry but I didn't figure out how to write a test for this ...

### CODE REVIEW

**Comment by tpounds** [comment]
@grongor Thanks for the pr! It looks like we need to update the fork of `errcheck`before we can support the newer options. @jirfag Any thoughts?

**Comment by ernado** [comment]
This can be done with `issues.exclude-rules` config for any linter and any file name regex:
```yml
issues:
  exclude-rules:
    - path: _test\.go
      linters: [errcheck]
```

**Comment by grongor** [comment]
@ernado nice, didn't think about that - thanks :)

**Comment by jirfag** [comment]
Hi!
I agree with @ernado - let's not create different ways to do one thing. Closing it, sorry.

**Comment by tpounds** [comment]
@jirfag It's probably ok to support the equivalent functionality when it exists in the dependency in order to maintain feature parity. We also need to make a pass at all of the golangci forked linters such as errcheck to bring them up to date.

**Comment by jirfag** [comment]
1. it will confuse users - how to disable some linter from tests. Is it more correct to disable it in linter settings or in `exclude-rules` or by `--tests`. We have 3 ways to do it. And `exclude-rules` and `--test` work differently: the first just excluded issues but loads/parses all test files, the second doesn't load/parse test files. We need to document it better. 
2. I see no benefit from this feature parity. If the user would like to disable `errcheck` for tests - they can use `exclude-rules`. Maybe we can document it better in `README` or `.golangci.yml`.
3. this pull request doesn't work: `WithoutTests` works only for [packages loading](https://github.com/kisielk/errcheck/blob/master/internal/errcheck/errcheck.go#L183). golangci-lint does packages loading itself.

**Comment by ernado** [comment]
Please use `exclude-rules` for this and open issue if other approach for handling such cases is needed.
Closing for now.

**Pull request closed without merging**
