### PR TITLE
Add instructions for setting up on GitLab CI

### PR DESCRIPTION
**Pull request by WhyNotHugo**

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Sample run of this setup: https://gitlab.com/WhyNotHugo/darkman/-/jobs/1467365726

**Comment by WhyNotHugo** [comment]
I just went through your CLA. I find it very harmful to FLOSS development and **do not agree to those terms**.

Please just close the PR if the contribution is unwelcome under an open source license.

**Comment by ldez** [comment]
Hello @WhyNotHugo, if you don't agree with the CLA, sadly we cannot accept your contribution.

If you think there is a problem with our CLA, I recommend opening an issue to discuss that.

**Comment by WhyNotHugo** [comment]
Is that something that's actually open to discussion though?

If so, I can bring it up with further details.

**Pull request closed without merging**
