### PR TITLE
docs: remove unused from config.LintersSettings

### LINKED ISSUE #3555: docs: unused configuration broken link
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

On the page https://golangci-lint.run/usage/linters

In the "Enabled by default" section in the end there is: "unused ⚙️" 

If you click on the ⚙️ for configuration it's a broken link: https://golangci-lint.run/usage/linters/#unused

### Version of golangci-lint

N/A

### Configuration file

N/A

### Go environment

N/A

### Verbose output of running

N/A

### Code example or link to a public repository

N/A

### PR DESCRIPTION
**Pull request by Antonboom**
Closes #3555

without extra changes opposite #3703

Closes #3703

### CODE REVIEW

**Comment by ldez** [comment]
#3555 is about a problem during the generation of the doc, this PR doesn't fix the problem.

**Comment by Antonboom** [comment]
> is about a problem during the generation of the doc

No, the problem is because your `if hasSettings(lc.Name())` returns `true` for `unused`.
I tested this fix, please pay more attention.

**Comment by ldez** [comment]
I tried it locally and the preview doesn't detect any changes:
Screenshot 2023-03-18 at 10-41-46 Linters golangci-lint

**Comment by ldez** [comment]
My fault, I was a problem locally, sorry.

**Review by ldez — APPROVED** [review]

**Pull request merged**
