### PR TITLE
Update assets for v1.34.0

### PR DESCRIPTION
**Pull request by denis-tingajkin**
Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>

Fixes: https://github.com/golangci/golangci-lint/runs/1618093797

This pr just makes
```
make assets/github-action-config.json
make update_netlify_state
make update_contributors_list
```

### CODE REVIEW

**Review by SVilgelm — CHANGES_REQUESTED** [review]
hmmm, the 1.34.0 is release, so this must contain v1.34.0 in assets

**Comment by ldez** [comment]
https://github.com/orgs/golangci/teams/team/discussions/5/comments/31

**Comment by denis-tingajkin** [comment]
https://github.com/orgs/golangci/teams/team/discussions/5/comments/32

PR is updated for v1.34.0

**Review by ldez — APPROVED** [review]
LGTM

**Review by SVilgelm — CHANGES_REQUESTED** [review]
Please update the [changelog file](https://github.com/golangci/golangci-lint/blob/v1.34.0/CHANGELOG.md). It's used in the generating the changeling in the roadmap section: https://golangci-lint.run/product/roadmap/#changelog

**Comment by denis-tingajkin** [comment]
@SVilgelm  Change log file was not updated since September... So I think it can be done in separate PR.

**Comment by ldez** [comment]
@SVilgelm this step is not documented in the process page https://golangci-lint.run/contributing/workflow/#new-releases

Maybe we have to improve a bit this documentation page.

**Comment by ldez** [comment]
@denis-tingajkin I will update your PR to add this chnagelog.

**Comment by denis-tingajkin** [comment]
@ldez  I feel this still can be done in separate PR :)

**Comment by SVilgelm** [comment]
@denis-tingajkin we are not in rush, let's do it here, especially @ldez wants to do it

**Comment by denis-tingajkin** [comment]
@SVilgelm  OK, Could you improve documentation for releases and add a point about the change log?

**Comment by SVilgelm** [comment]
> @SVilgelm OK, Could you improve documentation for releases and add a point about the change log?

I will check, I didn't work on this projects since September, need to check what was changed

**Review by SVilgelm — APPROVED** [review]
Looks good to me. Thank you

**Comment by ldez** [comment]
Updating a changelog of this type by hand is great pain.

It is impossible to maintain it properly.

We have to change this in order to use the changelog generated during releases and stop with the months.

**Comment by SVilgelm** [comment]
> Updating a changelog of this type by hand is great pain.
> 
> It is impossible to maintain it properly.
> 
> We have to change this in order to use the changelog generated during releases and stop with the months.

agree, but it's what we have now
And it's not so hard if updating every time for evry release instead of going it once in 3 months :-)

**Pull request merged**
