### PR TITLE
Update golangci.com config to latest 1.22.x release

### PR DESCRIPTION
**Pull request by tpounds**
Updates to latest 1.22.x release to fix failing checks.

### CODE REVIEW

**Comment by tpounds** [comment]
@jirfag I thought updating the config to a newer release would fix the previous issues but that doesn't seem to be the case. Any ideas?

**Comment by sagikazarmark** [comment]
Sadly golangci.com always lags behind the latest version 😕

**Comment by hanzei** [comment]
Does this resolve https://github.com/golangci/golangci-lint/issues/910?

**Comment by tpounds** [comment]
@hanzei This pr just updates the CI config here. The fix for the golang.com service is https://github.com/golangci/golangci-api/pull/161.

cc @jirfag

**Comment by jirfag** [comment]
thank you, I will update to v1.23.0

**Pull request merged**
