### PR TITLE
gosec: add G115 to default exclusions

### LINKED ISSUE #4935: v1.60.2 reports integer overflow conversion int -> int32 for conversion like int32(group) with group is an int
### Welcome

- [X] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Description of the problem

v1.60.2 starts to report "integer overflow conversion int -> int32 for conversion like int32(group) with group is an int", but v1.60.1 does not report this error.

### Version of golangci-lint

v1.60.2

### Configuration

Using v1.60.2

v1.60.1 is fine.

### Go environment

1.22.4

### Verbose output of running

G115: integer overflow conversion int -> int32 (gosec)
	drqsGroup := int32(group)

group is an int defined.

### A minimal reproducible example or link to a public repository

internal project. no link.

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

### PR DESCRIPTION
**Pull request by ldez**
Fixes #4935, #4939

Related to #4927

### CODE REVIEW

**Comment by ccoVeille** [comment]
Thanks, it will help a lot until gosec discussion ends

**Review by bombsimon — COMMENTED** [review]
Hmm, is this a good idea? In general I really don't like `exclude-use-default` (all rules should be up to the user to configure) and to me that's legacy that should be removed. It's been brought up in previous discussions (such as #4323, #2239 and #456).

As far as I can tell, G115 _is_ a valid check given it doesn't have false positives. So if this gets excluded by default and then gets fixed upstream we'd no longer warn about actual overflow and instead hide them from users that enables `gosec`.

And as far as I can tell from the linked issues, since we don't change existing exclusions due to backwards compatibility reasons that means that if we add this we can't remove it until a new major version. 

Also, isn't this (partly) fixed by https://github.com/securego/gosec/pull/1188 and more fixes are to come upstream?

**Comment by ldez** [comment]
We have no choice if we want to disable a rule inside gosec rather than using default exclusion.
I also always set it to `false` but at least we will reduce the noise for some users.

> As far as I can tell, G115 is a valid check given it doesn't have false positives.

Currently, it has false positives: `uint8 -> int64`, `uint8 -> int`, etc.

But https://github.com/securego/gosec/pull/1188 can reduce the problem.

**Comment by ldez** [comment]
Closed in favor of #4943

**Comment by bombsimon** [comment]
> We have no choice if we want to disable a rule inside gosec rather than using default exclusion.
> I also always set it to false but at least we will reduce the noise for some users.

Alright, thanks for clarifying! I get that the noise can be annoying but afaict `gosec` isn't one of the default enabled linters in `golangci-lint` so it's not something we need to suppress for users running without a config/default config at least. So given that the linter must be enabled by the user (specifically or with `enable-all`), an alternative that is easier to change could be to note this in the reference config.

I'm open to reconsidering this but if the manual bumping you just did solves the _new_ false positives and the old ones stay the same (or will be fixed in the near future) I think it would be nice to avoid extending this list.

**Comment by ldez** [comment]
> We have no choice if we want to disable a rule inside gosec rather than using default exclusion.

I want to add a more detailed explanation of this sentence:
gosec doesn't have a default configuration and doesn't allow a default configuration.
By using default exclusion, we let the user have the possibility to enable this rule without unnecessary complexity for us to handle interaction with `include/exclude`.

But, for now, we have another solution, so we are "safe" :smile_cat:

**Comment by proton-ab** [comment]
Quite ironic that this was marked as `won't fix` while you yourself recommend end-users to disable G115 (and people will - because it still ignores bound checks). In my opinion, telling users to ignore it creates more mess as users will inevitably forget to enable it back whenever its enabled back, while you (`golangci-lint` team) do follow `gosec` development closely (for regular updates) and could easily decide to re-enable it back once https://github.com/securego/gosec/pull/1189/files lands.

I really fail to see your logic in this decision.

**Comment by ldez** [comment]
I recommended disabling it as a workaround because of false positives just after the v1.60.2 release.
It was because there were no other solutions before creating a new release of golangci-lint.

- v1.60.2 -> G115 is enabled by default inside gosec but there are false positives
- AFTER v1.60.2 and BEFORE v1.60.3, there are 2 solutions: gosec fixes or default exclusions
   - I create this PR to add G115 to the default exclusions
   - I closed this PR BECAUSE gosec created a fix
- v1.60.3 -> the false positives of G115 are fixed

The logic in this decision is clear if you watch the chronology of the events.

**Pull request closed without merging**
