### PR TITLE
feat: add usestdlibvars

### PR DESCRIPTION
**Pull request by sashamelentyev**
A linter that detect the possibility to use variables/constants from the Go standard library.
https://github.com/sashamelentyev/usestdlibvars

### CODE REVIEW

**Comment by kamilsk** [comment]
Did you check context? For example `.WriteHeader(200) -> .WriterHeader(http.StatusOK)` is good, `.CallSomething(200) -> .CallSomething(http.StatusOK)` is bad.

**Comment by sashamelentyev** [comment]
Yes, I check func name WriteHeader, and check arg for this func

**Comment by sashamelentyev** [comment]
What about http.MethodGet, etc.?

I plan add this to next version. And after lint add to golangci-lint list

**Comment by ldez** [comment]
In order for a pull request adding a linter to be reviewed, the linter and the PR must follow some requirements.

### Pull Request Description

- [ ] It must have a link to the linter repository.
- [ ] It must provide a short description about the linter.

### Linter

- [ ] It must not be a duplicate of another linter or a rule of a linter. (the team will help to verify that)
- [ ] It must have a valid license and the file must contain the required information by the license, ex: author, year, etc.
- [ ] The linter repository must have a CI and tests.
- [ ] It must use [`go/analysis`](https://golangci-lint.run/contributing/new-linters/).
- [ ] It must have a valid tag, ex: `v1.0.0`, `v0.1.0`.
- [ ] It must not contain `init()`.
- [ ] It must not contain `panic()`, `log.fatal()`, `os.exit()`, or similar.
- [ ] It must not have false positives/negatives. (the team will help to verify that)
- [ ] It must have tests inside golangci-lint.

### The Linter Tests Inside Golangci-lint

- [ ] They must have at least one std lib import.
- [ ] They must work with `T=<name of the linter test file>.go make test_linters`. (the team will help to verify that)

### `.golangci.example.yml`

- [ ] The linter must be added to the list of available linters (alphabetical case-insensitive order).
    - `enable` and `disable` options
- [ ] If the linter has a configuration, the exhaustive configuration of the linter must be added (alphabetical case-insensitive order)
    - The values must be different from the default ones.
    - The default values must be defined in a comment.
    - The option must have a short description.

### Others Requirements

- [ ] The files (tests and linter) inside golangci-lint must have the same name as the linter.
- [ ] The `.golangci.yml` of golangci-lint itself must not be edited and the linter must not be added to this file.
- [ ] The linters must be sorted in the alphabetical order (case-insensitive) in the `Manager.GetAllSupportedLinterConfigs(...)` and `.golangci.example.yml`.
- [ ] The load mode (`WithLoadMode(...)`):
    - if the linter doesn't use types: `goanalysis.LoadModeSyntax`
    - `goanalysis.LoadModeTypesInfo` required `WithLoadForGoAnalysis()` in the `Manager.GetAllSupportedLinterConfigs(...)`
- [ ] The version in `WithSince(...)` must be the next minor version (`v1.X.0`) of golangci-lint.

### Recommendations

- [ ] The linter should not use SSA. (currently, SSA does not support generics)
- [ ] The linter repository should have a readme and linting.
- [ ] The linter should be published as a binary. (useful to diagnose bug origins)

---

The golangci-lint team will edit this comment to check the boxes before and during the review.

**This checklist does not imply that we will accept the linter.**

**Comment by ldez** [comment]
My current opinion: the linter needs to have a larger scope, currently this is too limited.
Also, I think that the amount off-positive can be really important.

**Comment by sashamelentyev** [comment]
@kamilsk @ldez added http method and time layouts. 
In http method case - checks only funcs NewRequest and NewRequestWithContext

**Comment by sashamelentyev** [comment]
Added full list of HTTP status codes

**Comment by ldez** [comment]
just a remark, for me, it's not "reuse" (`reusestdlibvars`) but "use" (`usestdlibvars`).

For me, "reuse" means "use again" or "use more".

**Comment by sashamelentyev** [comment]
I rename lint right now

**Comment by ldez** [comment]
Some remarks about the implementation:
- variable names that start with `_` are not Go idiomatic.
- the constants are hard-coded manually, this is a bit weak, you can either generate the code or use reflect or at least use the constants themself.
- the multiple calls to `i.Preorder` are useless and will impact the performance: use only one `Preorder` with a filter with several node types and a `switch` on the type of the node.

**Comment by sashamelentyev** [comment]
@ldez all done! Thank you for review!

**Comment by sashamelentyev** [comment]
@ldez please help me with function description [here](https://github.com/sashamelentyev/usestdlibvars/blob/main/pkg/analyzer/analyzer.go#L46) and [here](https://github.com/sashamelentyev/usestdlibvars/blob/main/pkg/analyzer/analyzer.go#L51)

**Comment by ldez** [comment]
The problem is not the description but the code, I will try to open a PR

**Comment by ldez** [comment]
Note: there is an already existing rule about HTTP status code inside staticcheck.

https://staticcheck.io/docs/checks/#ST1013

**Comment by sashamelentyev** [comment]
@ldez added settings

**Comment by sashamelentyev** [comment]
@ldez what need to do for merge?

**Comment by ldez** [comment]
I need time.

**Comment by sashamelentyev** [comment]
@ldez, forgive me for push, thank you for all what you do

**Comment by sashamelentyev** [comment]
Add default RPC path and struct elements support (http.Request & http.Response case)

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
