### PR TITLE
fix body close panic.

### PR DESCRIPTION
**Pull request by ldez**
Related to https://github.com/timakin/bodyclose/pull/14

Can be a fix for #608

### CODE REVIEW

**Comment by jirfag** [comment]
thank you!

**Comment by korya** [comment]
@jirfag Any chance you can make a patch release containing the fix?

**Comment by jirfag** [comment]
@korya sorry for the slow response.
I've publised [v1.18.0 release](https://github.com/golangci/golangci-lint/releases/tag/v1.18.0)

**Comment by korya** [comment]
Great! Thanks!

I really like what you are doing and I appreciate it a lot. However, I believe this project is a very important piece in the GO ecosystem today. After `gometalinter` was deprecated in favor of this project, it became the ultimate GO linter. This is a reason why I think it is bad for such a project to depend on a single person and be paralyzed when this person has no time to deal with it. This is why I think you need to consider adding more people who can merge PRs and make patch releases (this part probably can be automated).

Again, I really appreciate the work you are doing. Thanks a lot!

**Pull request merged**
