### PR TITLE
ifshort: deprecate linter

### PR DESCRIPTION
**Pull request by esimonov**
Hey team,

I would like to remove [ifshort](https://github.com/esimonov/ifshort) linter from the project.  It has gathered 10+ issues over the last year, mostly reporting false positives. And, as one may guess, I cannot find resources I could devote to fixing those issues. 

  This linter was a fun exercise, but I don't want it to annoy the community.

### CODE REVIEW

**Comment by ldez** [comment]
hello,

I understand your situation.

Instead of removing the linter, you will have to deprecate it.

**Comment by ldez** [comment]
@esimonov I did the job of deprecating your linter inside your PR.

Note that another solution can be to transfer the ownership of your linter to the golangci organization.

**Comment by esimonov** [comment]
@ldez Thank you for your understanding and timely response. Is there any more action required on my part?

**Comment by wwade** [comment]
> Note that another solution can be to transfer the ownership of your linter to the golangci organization.

If that does happen, please consider my https://github.com/esimonov/ifshort/issues/27 report for future inclusion in golangci :)

**Comment by ldez** [comment]
@esimonov Do you want to deprecate your linter or transfer it to the golangci organization?

**Comment by esimonov** [comment]
@ldez If possible, I would like to deprecate it.

**Review by ldez — APPROVED** [review]
LGTM

**Comment by s3rj1k** [comment]
This is sad, I actually like that linter :(

@esimonov maybe you can reconsider and transfer ownership to golangci organization?
I do not think that this transfer will somehow force you to support it, it's just a matter of license.

**Pull request merged**
