### PR TITLE
Add goBadWords Linter

### PR DESCRIPTION
**Pull request by Ghvstcode**
https://github.com/Ghvstcode/goBadWord

### CODE REVIEW

**Comment by ldez** [comment]
Also the linter repository contains a binary, can you remove it?

**Comment by SVilgelm** [comment]
Please use the `embed` feature to include the list of bad words, otherwise you will need to supply that json with golagnci-lint

**Comment by Ghvstcode** [comment]
> Please use the `embed` feature to include the list of bad words, otherwise you will need to supply that json with golagnci-lint

Hey @SVilgelm 👋🏼, What is the embed feature? & How do I add the list of bad words properly or supply the json file to golangci-lint

**Comment by Ghvstcode** [comment]
> This PR rewrites a lot of unrelated functionality. Can you please reset your branch and commit only related to your linter changes?

Sorry about that, Fixed!

**Comment by Ghvstcode** [comment]
> Also the linter repository contains a binary, can you remove it?
> 
> https://github.com/Ghvstcode/goBadWord/tree/main/cmd/badWord

Good catch! Fixed.

**Comment by ldez** [comment]
The "embed" approach will not work well with the "tools pattern" (tools defined in a go.mod file), it's preferable to not use [embed](https://pkg.go.dev/embed) in the context of golangci-lint. It's better to use a simple hardcoded list inside Go Code for the context of golangci-lint.

**Comment by butuzov** [comment]
What is the name of this tool - badwords, badword or gobadword?

**Comment by Ghvstcode** [comment]
> The "embed" approach will not work well with the "tools pattern" (tools defined in a go.mod file), it's preferable to not use [embed](https://pkg.go.dev/embed) in the context of golangci-lint. It's better to use a simple hardcoded list inside Go Code for the context of golangci-lint.

Aha, I see! Fixed. It’s a long list of words tho'

**Comment by butuzov** [comment]
- Help Entry is ~5 kb long. If you make it shorter you can help your own project
- Entry in help refer to keyword  is different than real keywords (-bad-words vs `-badWord`)
- How to use it (I haven't found readme or something)?
- project require LICENCE
- panics...
- it doesn't catch what it suppose to (i tested with variable names `foobar` and the same keyword).

@Ghvstcode this project to fresh even for review. Can you take a bit more work polishing it?

**Comment by Ghvstcode** [comment]
> here is what I have found:
> 
> * Help Entry is ~5 kb long. Make it shorter to help the project be more user-oriented.
> * Entry in help refer to keyword  is different than real keywords (`-bad-words` vs `-badWord`).
> * How to use it (I haven't found readme or something)?
> * golangci-lint linters require LICENCE
> * It panics at least in one place...
> * It doesn't catch what it suppose to (i tested with variable names `foobar` and the same keyword).
> 
> @Ghvstcode this project is way too fresh and untested even for review. Can you take a bit more work polishing it?

Hey, I would do some work on it and come back with another PR. Thanks for your time.

**Pull request closed without merging**
