### PR TITLE
Add tests, failures and errors attributes on testsuites

### PR DESCRIPTION
**Pull request by ced42**
The Junit output format doesn't validate the Jenkins XSD:
https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd

So, I have added tests, failures and errors attributes on testsuite elements.

### CODE REVIEW

**Comment by ced42** [comment]
Hello,

@jirfag , @ernado  I have an issue concerning the GITHUB_TOKEN on tests, could you tell me if it is on my side?

Regards,
Cédric.

**Comment by jirfag** [comment]
hi,
thank you,
the issue is that [secrets are not passed to workflows that are triggered by a pull request from a fork. Learn more](https://help.github.com/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets).
I need to think about what to do with that.

**Comment by ced42** [comment]
Hi,

In .github/workflows/tag.yml, I have found this line:
`GITHUB_TOKEN: ${{ secrets.GOLANGCI_LINT_TOKEN }}`
Shouldn't it be:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
(https://github.com/actions/create-release#example-workflow---create-a-release)

**Comment by jirfag** [comment]
you are right, thank you!
I've fixed it in a `master`, please, rebase on a `master` branch

**Comment by jirfag** [comment]
thank you!

**Pull request merged**
