### PR TITLE
Deprecate `Interfacer` linter

### PR DESCRIPTION
**Pull request by SVilgelm**
Add `Deprecated` function to config that accepts a message as a deprecation reason.
Print a warning if a deprecated linter is enabled.

Deprecate the Interfacer linter due to archived repository.

### CODE REVIEW

**Comment by SVilgelm** [comment]
output is:
```bash
~/icloud/projects/golangci-lint/golangci-lint run ./...
WARN [runner] The linter 'interfacer' is deprecated due to: The repository of the linter has been archived by the owner. 
```

**Comment by ldez** [comment]
>  level=warning msg="[runner] The linter 'interfacer' is deprecated due to: The repository of the linter has been archived by the owner."

The current test system will not work with a warning log.
At least we have to disable `interfacer` from our `.golangci.yml`

**Comment by SVilgelm** [comment]
> The current test system will not work with a warning log.
> At least we have to disable `interfacer` from our `.golangci.yml`

Yes, I think how can we ignore only the deprecated messages in tests

**Comment by ldez** [comment]
I think we can use `log.Infof` instead of `log.Warnf`

**Comment by SVilgelm** [comment]
but then it will not be printed, because the Info level is ignored by default

**Comment by ldez** [comment]
maybe we can add an option like `--fast` to skip the warning. :thinking:

**Comment by ldez** [comment]
Maybe we can reuse `Config.InternalTest` :thinking:

**Comment by ldez** [comment]
I have some good results here: https://github.com/ldez/golangci-lint/commit/270a1db6c72a62a11cdc845dbc9f943859104d96

**Comment by SVilgelm** [comment]
cool, please commit it here

**Comment by SVilgelm** [comment]
because I came up only with this:
```diff
diff --git a/pkg/commands/run.go b/pkg/commands/run.go
index 357e274..9c611a3 100644
--- a/pkg/commands/run.go
+++ b/pkg/commands/run.go
@@ -6,6 +6,7 @@ import (
        "io/ioutil"
        "log"
        "os"
+       "regexp"
        "runtime"
        "strings"
        "time"
@@ -483,8 +484,19 @@ func (e *Executor) setupExitCode(ctx context.Context) {
                return
        }
 
-       needFailOnWarnings := (os.Getenv("GL_TEST_RUN") == "1" || os.Getenv("FAIL_ON_WARNINGS") == "1")
-       if needFailOnWarnings && len(e.reportData.Warnings) != 0 {
+       glTestRun := os.Getenv("GL_TEST_RUN") == "1"
+       needFailOnWarnings := (glTestRun || os.Getenv("FAIL_ON_WARNINGS") == "1")
+       warnings := len(e.reportData.Warnings)
+       if glTestRun {
+               re := regexp.MustCompile("The linter '.+' is deprecated due to: .+")
+               for _, w := range e.reportData.Warnings {
+                       if re.MatchString(w.Text) {
+                               warnings--
+                       }
+               }
+       }
+
+       if needFailOnWarnings && warnings != 0 {
                e.exitCode = exitcodes.WarningInTest
                return
        }
```

**Comment by ldez** [comment]
Your approach seems also good maybe a bit harder to maintain :thinking:

**Comment by SVilgelm** [comment]
current output:
```bash
21-02-20 16:53 % ~/icloud/projects/golangci-lint/golangci-lint run ./...                   
WARN [runner] The linter 'interfacer' is deprecated due to: The repository of the linter has been archived by the owner. 
21-02-20 16:53 % echo $?
0

21-02-20 16:53 % FAIL_ON_WARNINGS=1 ~/icloud/projects/golangci-lint/golangci-lint run ./...
WARN [runner] The linter 'interfacer' is deprecated due to: The repository of the linter has been archived by the owner. 
21-02-20 16:53 % echo $?                                                                   
2
```

**Comment by ldez** [comment]
with my approach:
```console
$ ./golangci-lint run 
WARN [runner] The linter 'interfacer' is deprecated due to: The repository of the linter has been archived by the owner.
$ echo $?
2
```

```console
$ ./golangci-lint run --internal-cmd-test
$ echo $?
0
```

**Comment by SVilgelm** [comment]
I tested also with yours approach

**Comment by SVilgelm** [comment]
with my approach we will need to maintain same string in two places

**Comment by ldez** [comment]
yes, the base message must sync between 2 places.

A variation of your approach can be to apply the filtering in the logger:

```diff
func (lw LogWrapper) Warnf(format string, args ...interface{}) {
	lw.origLog.Warnf(format, args...)
	w := Warning{
		Tag:  strings.Join(lw.tags, "/"),
		Text: fmt.Sprintf(format, args...),
	}

+	re := regexp.MustCompile("The linter '.+' is deprecated due to: .+")
+	if re.MatchString(w.Text) {
+		return
+	}

	lw.rd.Warnings = append(lw.rd.Warnings, w)
}
```

**Comment by ldez** [comment]
the advantages of my approach:
- it can be reuse and extend
- easy to apply to all the tests

**Comment by ldez** [comment]
A variation of my approach can be to create a flag like `--skip-deprecated-linter-warn`

**Comment by SVilgelm** [comment]
@ldez approve it?

**Comment by ldez** [comment]
I have to remove a TODO before :wink:  https://github.com/golangci/golangci-lint/pull/1755/files#diff-ea835ba5eff883f863af2b9a490f5ccebd8ce3618c8d6d73f5ca15712e4f1e49R209

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
