### PR TITLE
cleanup: Remove completion subcommand

### PR DESCRIPTION
**Pull request by sayboras**
## Description

With #2105, completion subcommand will be automatically added. Consider
that golangci-lint didn't do anything special with completion, it's better
to just remove it from codebase.

Signed-off-by: Tam Mach <sayboras@yahoo.com>

## Testing

Testing was done as per below

```
$ ./golangci-lint completion -h

Generate the autocompletion script for golangci-lint for the specified shell.
See each sub-command's help for details on how to use the generated script.

Usage:
  golangci-lint completion [command]

Available Commands:
  bash        generate the autocompletion script for bash
  fish        generate the autocompletion script for fish
  powershell  generate the autocompletion script for powershell
  zsh         generate the autocompletion script for zsh

```

### CODE REVIEW

**Review by bombsimon — APPROVED** [review]
Nice!

**Comment by MarvinJWendt** [comment]
Hi @sayboras, why was the completion command removed? It's auto generated from all subcommands and flags, there is no need to "do anything special with completion", it "just works" :)

**Comment by ldez** [comment]
The completion command is still here, right now it's auto-generated.
We just removed the old code to generate manually the command.

**Comment by MarvinJWendt** [comment]
Oh okay I see, thanks @ldez.

**Pull request merged**
