### PR TITLE
Add wrapcheck linter

### PR DESCRIPTION
**Pull request by tomarrell**
This PR introduces the [wrapcheck](https://github.com/tomarrell/wrapcheck) linter.

There is a more extensive write-up about the functionality and justification for this linter here: https://blog.tomarrell.com/post/introducing_wrapcheck_linter_for_go

The test added here is just a minimal example, there is a more [extensive suite](https://github.com/tomarrell/wrapcheck/tree/master/wrapcheck/testdata) included in the repository.

### CODE REVIEW

**Comment by Nivl** [comment]
Looks good to me, I'll approve once you fixed the conflicts.

**Comment by tomarrell** [comment]
Cheers for that @Nivl, have resolved the conflict. Should be good to go.

**Review by Nivl — APPROVED** [review]
Looks good, thanks!

**Comment by tomarrell** [comment]
@Nivl, just wondering if there is anything else that needs to be done before this can be merged? I don't have write access.

Thanks! 🙂

**Comment by bombsimon** [comment]
Nope, let's merge this!

**Pull request merged**
