### PR TITLE
Use errcheck from main repo instead of golangci-lint fork

### LINKED ISSUE #882: errcheck doesn't detect all unchecked type assertion
Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```bash
$ golangci-lint --version
golangci-lint has version 1.21.0 built from 645e794 on 2019-10-15T18:16:56Z
```

</details>

<details><summary>Config file</summary>

```bash
$ cat .golangci.yml
run:
  timeout: "10m"
linters:
  disable-all: true
  enable:
    - "bodyclose"
    - "deadcode"
    - "depguard"
    - "errcheck"
    - "gocritic"
    - "gocyclo"
    - "gofmt"
    - "goimports"
    - "golint"
    - "govet"
    - "ineffassign"
    - "megacheck"
    - "misspell"
    - "nakedret"
    - "structcheck"
    - "unconvert"
    - "unparam"
    - "varcheck"
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - errors
      - reflect
      - unsafe
      - github.com/pkg/errors
  errcheck:
    check-type-assertions: true
  gocyclo:
    min-complexity: 10
  govet:
    enable-all: true
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
```

</details>

<details><summary>Go environment</summary>

```bash
$ go version && go env
go version go1.13.5 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pierre/.cache/go-build"
GOENV="/home/pierre/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pierre/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/pierre/.gimme/versions/go1.13.5.src"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/pierre/.gimme/versions/go1.13.5.src/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pierre/gosrc/github.com/xxx/yyy/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build810139123=/tmp/go-build -gno-record-gcc-switches"
```

</details>

<details><summary>Verbose output of running</summary>

```bash
$ golangci-lint run -v
INFO [config_reader] Config search paths: [./ /home/pierre/gosrc/github.com/xxx/yyy /home/pierre/gosrc/github.com/xxx /home/pierre/gosrc/github.com /home/pierre/gosrc /home/pierre /home /] 
INFO [config_reader] Used config file .golangci.yml 
INFO [lintersdb] Active 20 linters: [bodyclose deadcode depguard errcheck gocritic gocyclo gofmt goimports golint gosimple govet ineffassign misspell nakedret staticcheck structcheck unconvert unparam unused varcheck] 
INFO [loader] Go packages loading at mode 575 (exports_file|imports|compiled_files|deps|files|name|types_sizes) took 235.781777ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 24.339956ms 
INFO [runner/goanalysis_metalinter/goanalysis] analyzers took 25.433211455s with top 10 stages: buildssa: 9.13999065s, goimports: 1.69246075s, gofmt: 1.231308728s, unparam: 922.471835ms, golint: 834.866973ms, ineffassign: 768.164647ms, misspell: 738.716443ms, gocritic: 684.814951ms, SA4014: 671.62614ms, deadcode: 632.376094ms 
INFO [runner/unused/goanalysis] analyzers took 1.973672294s with top 10 stages: buildssa: 1.441568036s, U1000: 532.104258ms 
INFO [runner] Issues before processing: 18, after processing: 0 
INFO [runner] Processors filtering stat (out/in): filename_unadjuster: 18/18, identifier_marker: 18/18, exclude: 18/18, path_prettifier: 18/18, skip_files: 18/18, autogenerated_exclude: 18/18, nolint: 0/18, cgo: 18/18, skip_dirs: 18/18, exclude-rules: 18/18 
INFO [runner] processing took 5.717866ms with stages: nolint: 5.046802ms, path_prettifier: 242.312µs, identifier_marker: 211.745µs, autogenerated_exclude: 109.443µs, skip_dirs: 98.829µs, cgo: 4.679µs, filename_unadjuster: 1.501µs, max_same_issues: 683ns, skip_files: 281ns, diff: 255ns, max_from_linter: 241ns, uniq_by_line: 187ns, exclude-rules: 187ns, path_shortener: 185ns, max_per_file_from_linter: 182ns, source_code: 182ns, exclude: 172ns 
INFO [runner] linters took 3.431985751s with stages: goanalysis_metalinter: 2.888784135s, unused: 537.425552ms 
INFO File cache stats: 382 entries of total size 1.2MiB 
INFO Memory: 38 samples, avg is 368.0MB, max is 610.1MB 
INFO Execution took 3.696656595s
```

</details>

I've configured errcheck to report unchecked type assertion.
However, in this code:
```go
if filter["messages_sent.messageid"].(map[string]interface{})["$ne"] != nil {
```
the type assertion is not checked, but it's not reported.
`filter` is a `bson.M` from `github.com/globalsign/mgo/bson`.

### LINKED ISSUE #959: Update errcheck to latest version
This maybe the wrong place for it so close it if it is but https://github.com/golangci/errcheck does not have the ability to create an issue.

But I wanted to open it up and get feedback on thoughts regarding updating that forked repo to have the latest version of what the forked repo has https://github.com/kisielk/errcheck. 

The thing that golangci version is currently missing is the embedded interface walker stuff found here. 

https://github.com/kisielk/errcheck/blob/master/internal/errcheck/embedded_walker.go

I believe updating that would resolve issue #656 and hopefully #657

### LINKED ISSUE #1194: embedded errcheck linter errors are not the same as with running standalone errcheck
Hi, thanks for creating this gh action

I receive inconsistent results with this action considering the `errcheck` linter. If I run the latest `errcheck` downloaded with `go get` I receive an extensive report, whereas running golang-ci-lint action with default configuration I see just a fraction of errcheck linter errors.
What could be the potential reason? This is my test run log:

```
2020-06-21T07:53:29.1627489Z Running [/home/runner/golangci-lint-1.27.0-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
2020-06-21T07:53:30.6448589Z ##[error]Error return value of `reqCapability` is not checked (errcheck)
2020-06-21T07:53:30.6452862Z ##[error]Error return value of `viper.BindPFlag` is not checked (errcheck)
2020-06-21T07:53:30.6453512Z ##[error]Error return value of `getCmd.MarkFlagRequired` is not checked (errcheck)
2020-06-21T07:53:30.6454304Z ##[error]Error return value of `viper.BindPFlag` is not checked (errcheck)
2020-06-21T07:53:30.6454990Z ##[error]Error return value of `viper.BindPFlag` is not checked (errcheck)
2020-06-21T07:53:30.6455423Z ##[error]Error return value of `server.grpcServer.Serve` is not checked (errcheck)
2020-06-21T07:53:30.6455859Z ##[error]Error return value of `viper.ReadInConfig` is not checked (errcheck)
2020-06-21T07:53:30.6456332Z ##[error]Error return value of `subscribeCmd.MarkFlagRequired` is not checked (errcheck)
```

and the output of the `errcheck` is far more complete for the same commit https://gist.github.com/hellt/9f02f6c8a2e768fb3d9d25cbcb6f432b

### LINKED ISSUE #1274: Update errcheck to address false positives
It looks like the forked errcheck package (https://github.com/golangci/errcheck) is two years behind its current upstream (https://github.com/kisielk/errcheck). There are unfortunately some custom commits, so a trivial sync is not possible. What would it take to update it?

Is it possible to upstream some changes and avoid the use of a fork to ensure easy upgrades? (@kisielk @jirfag ?)

I ran into a false-positive `errcheck` warning with the following code:
```go
package main

import (
	"crypto/sha256"
	"fmt"
)

func main() {
	h := sha256.New()
	h.Write([]byte("food"))
	fmt.Println(h.Sum(nil))
}
```

Using the `golangci/golangci-lint:v1.27.0` Docker image it outputs:
```
main.go:10:9: Error return value of `h.Write` is not checked (errcheck)
	h.Write([]byte("food"))
	       ^
```
This issue has been solved upstream two years ago via https://github.com/kisielk/errcheck/pull/137.

Related issues:
-  https://github.com/golangci/golangci-lint/issues/1194
- Attempt at updating the fork: https://github.com/golangci/errcheck/pull/4

### PR DESCRIPTION
**Pull request by SVilgelm**
Closes #1274
Closes #1194
Closes #882
Closes #959

https://github.com/kisielk/errcheck/compare/8050dd7cc11578becd8622667107bb21a7baf451...master
https://github.com/golangci/errcheck/compare/8050dd7cc11578becd8622667107bb21a7baf451...master

Depends on: 
* ~~https://github.com/kisielk/errcheck/pull/185~~ 
* ~~https://github.com/kisielk/errcheck/pull/197~~

### CODE REVIEW

**Comment by sayboras** [comment]
Mark as draft PR to avoid showing up in review list.

**Comment by leventov** [comment]
Hello @SVilgelm @sayboras, maybe we could reignite this PR because kisielk/errcheck#185 is now merged?

**Comment by ldez** [comment]
The previous exclusion rule (`Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked`) will not work because of the change of the value of `UncheckedError.FuncName`

The current output:
```
scripts/expand_website_templates/main.go:61:17: Error return value of `os.Stdout.Write` is not checked (errcheck)
        os.Stdout.Write([]byte{})
                       ^
scripts/expand_website_templates/main.go:149:23: Error return value of `resp.Body.Close` is not checked (errcheck)
        defer resp.Body.Close()
                             ^
```

The output with the PR:
```
scripts/expand_website_templates/main.go:61:17: Error return value of `(*os.File).Write` is not checked (errcheck)
        os.Stdout.Write([]byte{})
                       ^
scripts/expand_website_templates/main.go:149:23: Error return value of `(io.Closer).Close` is not checked (errcheck)
        defer resp.Body.Close()
                             ^
```

https://github.com/golangci/golangci-lint/blob/306816ec8544f5b2363f06bab72547484874656d/pkg/config/config.go#L39-L46

**Comment by ldez** [comment]
I don't see many solutions :cry: 

1. We drop the exclusions rule, but I think it's not a good idea.
2. We add `UncheckedError.Line` into the message, but `Line` contains the real line of code.

In all the cases, it's a breaking change.

**Comment by SVilgelm** [comment]
@ldez  Here is the PR to original repo: https://github.com/kisielk/errcheck/pull/197
to have a backward compatible name in the message

so it should solve the problem with dropping the exclusions rule

**Comment by SVilgelm** [comment]
@golangci/team Please review, it's still blocked until a new release of the `errcheck`

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
