### PR TITLE
update staticcheck to v2020.1.3

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/dominikh/go-tools/compare/2019.2.3...2020.1.3

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks!

**Comment by ksoichiro** [comment]
It's great that staticcheck was updated!
But unfortunately it seems `unused` linter is broken after this change...
Some false positives are detected in our private repo.
I'll check later and share minimal reproducible codes.

**Comment by ernado** [comment]
Hey @ksoichiro, new version was not released. Are you building golangci by yourself?

**Comment by ksoichiro** [comment]
Thank you for your response @ernado.
Yes, I know that.
We detected it because our repo is not properly configured, and golangci-lint was built on our CI.
We've already fixed our CI to get the latest tagged version,
but I commented to share it because I think it would be an issue if you release the current master branch.

**Comment by ernado** [comment]
Thank you, @ksoichiro, I've just wanted to double-check.

Will wait until a way to reproduce that problem, so we can debug and fix that issue before releasing new version.

**Comment by ksoichiro** [comment]
I found that it was not false positive, it was really unused!
It was a variable in our test code, which was not reachable because it was marked as skip: `runtime.Goexit()` was called there.
It seems newer version of staticcheck is aware of `runtime.Goexit()`.
I'm really sorry for bothering you, but I hope this helps someone.

**Comment by ernado** [comment]
Thank you very much, @ksoichiro!
> I'm really sorry for bothering you

No worries, I am very grateful for your help.

**Comment by thaJeztah** [comment]
Good to hear, thanks!

**Comment by ernado** [comment]
I have no idea why staticcheck update is causing those issues, but I had to revert it, sorry.

**Comment by thaJeztah** [comment]
I saw it yes. That's unfortunate; hope you're able to find what causes it

**Comment by jirfag** [comment]
Updating `staticcheck` back in #1063

**Comment by thaJeztah** [comment]
Thanks for keeping me updated!

**Pull request merged**
