### PR TITLE
add linter zerologlint

### PR DESCRIPTION
**Pull request by ykadowak**
I'd like to add https://github.com/ykadowak/zerologlint. 
This linter detects the wrong usage of `zerolog` that a user forgets to dispatch with `Send` or `Msg`.

I'm not sure if this linter is applicable to this repository because this is specific only for `zerolog`. Also this linter uses SSA.

### CODE REVIEW

**Comment by ldez** [comment]
In order for a pull request adding a linter to be reviewed, the linter and the PR must follow some requirements.

- [ ] The CLA must be signed

### Pull Request Description

- [ ] It must have a link to the linter repository.
- [ ] It must provide a short description of the linter.

### Linter

- [ ] It must not be a duplicate of another linter or a rule of a linter. (the team will help to verify that)
- [ ] It must have a valid license (AGPL is not allowed) and the file must contain the required information by the license, ex: author, year, etc.
- [ ] The linter repository must have a CI and tests.
- [ ] It must use [`go/analysis`](https://golangci-lint.run/contributing/new-linters/).
- [ ] It must have a valid tag, ex: `v1.0.0`, `v0.1.0`.
- [ ] It must not contain `init()`.
- [ ] It must not contain `panic()`, `log.fatal()`, `os.exit()`, or similar.
- [ ] It must not have false positives/negatives. (the team will help to verify that)
- [ ] It must have tests inside golangci-lint.

### The Linter Tests Inside Golangci-lint

- [ ] They must have at least one std lib import.
- [ ] They must work with `T=<name of the linter test file>.go make test_linters`. (the team will help to verify that)

### `.golangci.reference.yml`

- [ ] The linter must be added to the list of available linters (alphabetical case-insensitive order).
    - `enable` and `disable` options
- [ ] If the linter has a configuration, the exhaustive configuration of the linter must be added (alphabetical case-insensitive order)
    - The values must be different from the default ones.
    - The default values must be defined in a comment.
    - The option must have a short description.

### Others Requirements

- [ ] The files (tests and linter) inside golangci-lint must have the same name as the linter.
- [ ] The `.golangci.yml` of golangci-lint itself must not be edited and the linter must not be added to this file.
- [ ] The linters must be sorted in the alphabetical order (case-insensitive) in the `Manager.GetAllSupportedLinterConfigs(...)` and `.golangci.reference.yml`.
- [ ] The load mode (`WithLoadMode(...)`):
    - if the linter doesn't use types: `goanalysis.LoadModeSyntax`
    - `goanalysis.LoadModeTypesInfo` required `WithLoadForGoAnalysis()` in the `Manager.GetAllSupportedLinterConfigs(...)`
- [ ] The version in `WithSince(...)` must be the next minor version (`v1.X.0`) of golangci-lint.

### Recommendations

- [ ] The linter should not use SSA. (currently, SSA does not support generics)
- [ ] The linter repository should have a readme and linting.
- [ ] The linter should be published as a binary. (useful to diagnose bug origins)

---

The golangci-lint team will edit this comment to check the boxes before and during the review.

If the author of the PR is a member of the golangci-lint team, he should not edit this message.

The code review will start after the completion of those checkboxes (except for the specific items that the team will help to verify).

**This checklist does not imply that we will accept the linter.**

**Comment by SVilgelm** [comment]
I'm really interesting in this linter, and tried it on a huge private repo, got bunch of panics, mostly on the generated pb (proto) files.
let me debug it first, will report back here

**Comment by SVilgelm** [comment]
here is the fix: https://github.com/ykadowak/zerologlint/pull/2

**Comment by ykadowak** [comment]
- add @SVilgelm's fix and bump version [bf0951e](https://github.com/golangci/golangci-lint/pull/3726/commits/bf0951ef54e586d47afdc18dad54338c8c634a62) and add test case for it 
[fb99cb5](https://github.com/golangci/golangci-lint/pull/3726/commits/fb99cb5f1dc1769b9761092bd5d1ccf7110aa1c6)
- use stdlib in the test case [550d46c](https://github.com/golangci/golangci-lint/pull/3726/commits/550d46cc6941e390aeed49d068d84c56e0c0f505)

**Review by spatecon — APPROVED** [review]

**Comment by ykadowak** [comment]
@ldez 
Gentle ping. Perhaps is there anything left that I'm supposed to do?

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
