### PR TITLE
feat: Include custom linters in `enable-all`

### PR DESCRIPTION
**Pull request by yuqengo**
Related to https://github.com/golangci/golangci-lint/issues/3080

.golangci.yml
```
linters-settings:
  custom:
    example:
      path: ./example.so

linters:
  enable-all: true
```
Custom linters work for `enable-all`.

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

for security reasons, I think it's a bad idea to do that.

**Comment by yuqengo** [comment]
Hello, Thanks for review!

What security reasons do you have?

**Comment by ldez** [comment]
I thought about the subject and I think there is a bug because the activation of plugins should be done by default. https://github.com/golangci/golangci-lint/blob/011252127f53cf6a0f2b28dc97fed55508575b09/pkg/lint/lintersdb/manager.go#L983

The current implementation inside golangci-lint has some design problems.

I think I will fix the design problem and the behavior of the plugin in another PR.

**Comment by yuqengo** [comment]
@ldez 
hello idez !

> The current implementation inside golangci-lint has some design problems.
> I think I will fix design problems and the behavior of the plugin in another PR.

If you respond with another PR, Should this PR be closed ?

**Pull request closed without merging**
