### PR TITLE
Add MIPS arch support

### LINKED ISSUE #935: Add mips architecture support
Now golangci-lint does not support MIPS arch:
```
golangci/golangci-lint crit platform linux/mips64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/golangci/golangci-lint/issues/new
```

I can do the porting and test if possible.

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

Fix #935

Refer to [prometheus release](https://github.com/prometheus/prometheus/releases), support `mips64` and `mips64le`.

### CODE REVIEW

**Comment by ernado** [comment]
Thank you! We should check that goreleaser will build project with such config.

I'll do it today, or you can try to do it (there should be something like snapshot mode in goreleaser).

**Comment by ernado** [comment]
I've tried to generate binaries with `goreleaser release --rm-dist --snapshot`, but got artifacts for MIPS:
```console
$ goreleaser release --rm-dist --snapshot

   • releasing using goreleaser 0.125.0...
   • loading config file       file=.goreleaser.yml
   • RUNNING BEFORE HOOKS
   • LOADING ENVIRONMENT VARIABLES
      • pipe skipped              error=publishing is disabled
   • GETTING AND VALIDATING GIT STATE
      • releasing v1.23.2, commit 9b3e3cfbc50567069b5c78de8217bbc94c7936a2
      • pipe skipped              error=disabled during snapshot mode
   • PARSING TAG      
   • SETTING DEFAULTS 
      • LOADING ENVIRONMENT VARIABLES
      • SNAPSHOTING      
      • GITHUB/GITLAB/GITEA RELEASES
      • PROJECT NAME     
      • BUILDING BINARIES
      • ARCHIVES         
      • LINUX PACKAGES WITH NFPM
      • SNAPCRAFT PACKAGES
      • CALCULATING CHECKSUMS
      • SIGNING ARTIFACTS
      • DOCKER IMAGES    
      • ARTIFACTORY      
      • BLOB             
      • HOMEBREW TAP FORMULA
      • SCOOP MANIFEST   
   • SNAPSHOTING      
   • CHECKING ./DIST  
      • --rm-dist is set, cleaning it up
   • WRITING EFFECTIVE CONFIG FILE
      • writing                   config=dist/config.yaml
   • GENERATING CHANGELOG
      • pipe skipped              error=not available for snapshots
   • BUILDING BINARIES
      • building                  binary=/src/golangci-lint/dist/golangci-lint_freebsd_386/golangci-lint
      • building                  binary=/src/golangci-lint/dist/golangci-lint_darwin_amd64/golangci-lint
      • building                  binary=/src/golangci-lint/dist/golangci-lint_linux_arm_6/golangci-lint
      • building                  binary=/src/golangci-lint/dist/golangci-lint_linux_s390x/golangci-lint
      • building                  binary=/src/golangci-lint/dist/golangci-lint_freebsd_amd64/golangci-lint
      • building                  binary=/src/golangci-lint/dist/golangci-lint_freebsd_arm_6/golangci-lint
      • building                  binary=/src/golangci-lint/dist/golangci-lint_freebsd_arm_7/golangci-lint
      • building                  binary=/src/golangci-lint/dist/golangci-lint_linux_arm_7/golangci-lint
      • building                  binary=/src/golangci-lint/dist/golangci-lint_linux_ppc64le/golangci-lint
      • building                  binary=/src/golangci-lint/dist/golangci-lint_windows_386/golangci-lint.exe
      • building                  binary=/src/golangci-lint/dist/golangci-lint_darwin_386/golangci-lint
      • building                  binary=/src/golangci-lint/dist/golangci-lint_windows_amd64/golangci-lint.exe
      • building                  binary=/src/golangci-lint/dist/golangci-lint_linux_amd64/golangci-lint
      • building                  binary=/src/golangci-lint/dist/golangci-lint_linux_arm64/golangci-lint
      • building                  binary=/src/golangci-lint/dist/golangci-lint_linux_386/golangci-lint
   • ARCHIVES         
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-freebsd-amd64.tar.gz
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-darwin-amd64.tar.gz
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-linux-s390x.tar.gz
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-linux-386.tar.gz
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-freebsd-armv7.tar.gz
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-linux-armv6.tar.gz
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-windows-amd64.zip
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-linux-armv7.tar.gz
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-freebsd-386.tar.gz
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-freebsd-armv6.tar.gz
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-linux-amd64.tar.gz
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-darwin-386.tar.gz
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-linux-ppc64le.tar.gz
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-linux-arm64.tar.gz
      • creating                  archive=dist/golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-windows-386.zip
   • LINUX PACKAGES WITH NFPM
   • SNAPCRAFT PACKAGES
   • CALCULATING CHECKSUMS
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-windows-386.zip
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-linux-armv6.tar.gz
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-freebsd-amd64.tar.gz
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-linux-386.tar.gz
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-linux-s390x.tar.gz
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-darwin-amd64.tar.gz
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-freebsd-armv7.tar.gz
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-darwin-386.tar.gz
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-linux-armv7.tar.gz
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-freebsd-386.tar.gz
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-freebsd-armv6.tar.gz
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-linux-ppc64le.tar.gz
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-linux-amd64.tar.gz
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-windows-amd64.zip
      • checksumming              file=golangci-lint-SNAPSHOT-9b3e3cfbc50567069b5c78de8217bbc94c7936a2-linux-arm64.tar.gz
   • SIGNING ARTIFACTS
      • pipe skipped              error=artifact signing is disabled
   • DOCKER IMAGES    
      • building docker image     image=golangci/golangci-lint:latest-alpine
      • building docker image     image=golangci/golangci-lint:latest
      • pipe skipped              error=publishing is disabled
   • PUBLISHING       
      • pipe skipped              error=publishing is disabled
   • release succeeded after 10.56s
```

I'm not sure what I'm doing wrong, seems like config is fine :(

**Comment by daixiang0** [comment]
@ernado I test at local:
```
Step 4/4 : CMD ["golangci-lint"]
 ---> Running in 26612faae082
Removing intermediate container 26612faae082
 ---> 1ba4c0b878e8
Successfully built 1ba4c0b878e8
Successfully tagged golangci/golangci-lint:latest-alpine
Successfully tagged golangci/golangci-lint:v0.0.0-alpine
Successfully tagged golangci/golangci-lint:v0.0-alpine

      • pipe skipped              error=publishing is disabled
   • PUBLISHING       
      • pipe skipped              error=publishing is disabled
   • release succeeded after 423.64s

[root golangci-lint]# echo $?
0
[root golangci-lint]# 
```

Enable debug mode with `--debug`, no more error info.

**Comment by ernado** [comment]
I see that there are no error, but I can't find any generated MIPS binary in dist.

**Comment by daixiang0** [comment]
@ernado i have found the root cause, refer to https://goreleaser.com/customization/#Builds and https://golang.org/doc/install/source#environment.
New commit would generate mips binarys.

**Comment by ernado** [comment]
If we decided to enable both hardfloat and softfloat, I'll leave this as reference: https://github.com/goreleaser/goreleaser/issues/1329

LGTM

**Comment by caarlos0** [comment]
New version is out, should fix the issue, sorry for the trouble :) 

https://github.com/goreleaser/goreleaser/releases/tag/v0.126.0

**Comment by ernado** [comment]
There were no trouble, I've referenced that issue just as memo, sorry for bothering and thanks for following :)

**Pull request merged**
