### PR TITLE
add ifacecapture lint

### PR DESCRIPTION
**Pull request by dgunay**
Recently wrote a linter that I think some may find helpful: https://github.com/dgunay/ifacecapture

## What it does 

It was originally written to try and find this specific mistake with an interface I use at work:

```go
type Database interface {
    Transaction(tx Database)
    DoQuery()
}

func doDatabaseStuff(db Database) {
    db.Transaction(func(tx Database) { // tx is a transaction handle
        db.DoQuery() 
        // the programmer probably meant to use the transaction handle "tx", but
        // accidentally used the outer scope variable "db"
    })
}
```

### Issues

~Seems like the `pass.TypesInfo` is nil when running under golangci-lint, which the linter unfortunately relies on. Still looking into why.~ added type info for it, now it runs.

My machine is running afoul of https://github.com/golang/go/issues/52495 so I'm still figuring that one out

~Need to update the repo with some more basic housekeeping (license, etc)~  I have added a license, removed init(), and removed all panics/fatals/exits from my code.

### CODE REVIEW

**Comment by ldez** [comment]
In order for a pull request adding a linter to be reviewed, the linter and the PR must follow some requirements.

### Pull Request Description

- [ ] It must have a link to the linter repository.
- [ ] It must provide a short description about the linter.

### Linter

- [ ] It must not be a duplicate of another linter or a rule of a linter. (the team will help to verify that)
- [ ] It must have a valid license and the file must contain the required information by the license, ex: author, year, etc.
- [ ] It must use [`go/analysis`](https://golangci-lint.run/contributing/new-linters/).
- [ ] It must have a valid tag, ex: `v1.0.0`, `v0.1.0`.
- [ ] It must not contain `init()`.
- [ ] It must not contain `panic()`, `log.fatal()`, `os.exit()`, or similar.
- [ ] It must not have false positives/negatives. (the team will help to verify that)
- [ ] It must have tests inside golangci-lint.

### The Linter Tests Inside Golangci-lint

- [ ] They must have at least one std lib import.
- [ ] They must work with `T=<name of the linter test file>.go make test_linters`. (the team will help to verify that)

### `.golangci.example.yml`

- [ ] The linter must be added to the list of available linters (alphabetical case-insensitive order).
  - `enable` and `disable` options
- [ ] If the linter has a configuration, the exhaustive configuration of the linter must be added (alphabetical case-insensitive order)
  - The values must be different from the default ones.
  - The default values must be defined in a comment.
  - The option must have a short description.

### Others Requirements

- [ ] The files (tests and linter) inside golangci-lint must have the same name as the linter.
- [ ] The `.golangci.yml` of golangci-lint itself must not be edited and the linter must not be added to this file.
- [ ] The linters must be sorted in the alphabetical order (case-insensitive) in the `Manager.GetAllSupportedLinterConfigs(...)` and `.golangci.example.yml`.
- [ ] The load mode (`WithLoadMode(...)`):
  - if the linter doesn't use types: `goanalysis.LoadModeSyntax`
  - `goanalysis.LoadModeTypesInfo` required `WithLoadForGoAnalysis()` in the `Manager.GetAllSupportedLinterConfigs(...)`
- [ ] The version in `WithSince(...)` must be the next minor version (`v1.X.0`) of golangci-lint.

### Recommendations

- [ ] The linter should not use SSA. (currently, SSA does not support generics)
- [ ] The linter repository should have a CI, tests, a readme and linting.
- [ ] The linter should be published as a binary. (useful to diagnose bug origins)

---

The golangci-lint team will edit this comment to check the boxes before and during the review.

**This checklist does not imply that we will accept the linter.**

**Comment by dgunay** [comment]
@ldez Hi - been a while. Would like to note that I have since complied with the following recommendations (still working on the others):

>  - The linter repository should have a CI, tests, a readme and linting.
>  - The linter should be published as a binary. (useful to diagnose bug origins)

**Comment by ldez** [comment]
The PR still does not comply with the checklist and there are some typos in the code.

**Comment by Antonboom** [comment]
@dgunay, hi!

Please add an "Installation" section to the README.

Also, I tried your linter and got error:
```
$ ifacecapture ./...
ifacecapture: internal error: package "sync" without types was imported from "runtime/cgo"
```

```
$ go version
go version go1.21.0 darwin/arm64
```

**Comment by ldez** [comment]
I will close this PR because:
- The PR does not meet the requirements of the checklist.
- https://github.com/golangci/golangci-lint/pull/2830#issuecomment-1742038048
- No feedback for a long time from the PR author.
- The code of golangci-lint has changed since 2022.

Feel free to open a new PR, when the linter and the implementation inside golangci-lint will be updated.

**Pull request closed without merging**
