### PR TITLE
build(deps): bump github.com/golangci/misspell 0.4.0 to 0.4.1

### LINKED ISSUE #3406: misspell ignore-words doesn't seem to be working
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

I've tried using this:

```
  misspell:
    locale: US
    ignore-words:
      - Dialogue

```

and if I have the following in my golang code:

```
type Test struct {
	Dialogue string
}
```

Dialogue is replaced wth Dialog

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.46.2 built from (unknown, mod sum: "h1:o90t/Xa6dhJbvy8Bz2RpzUXqrkigp19DLStMolTZbyo=") on (unknown)
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
linters-settings:
  misspell:
    locale: US
    ignore-words:
      - Dialogue
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.19.2 linux/arm64
GO111MODULE=""
GOARCH="arm64"
GOBIN="/go/bin"
GOCACHE="/home/vscode/.cache/go-build"
GOENV="/home/vscode/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspaces/my-project/go.mod"
GOWORK="/workspaces/my-project/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3362665096=/tmp/go-build -gno-record-gcc-switches"
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
`Dialogue` is a misspelling of `Dialog` (misspell)
        // Dialogue
```

</details>

### Code example or link to a public repository

<details>

```go
type Test struct {
	Dialogue string
}
```

Dialogue gets replaced with Dialog

</details>

### PR DESCRIPTION
**Pull request by ldez**
misspell: convert ignore-words to lowercase

https://github.com/golangci/misspell/compare/v0.4.0...v0.4.1

Fixes #3406

### CODE REVIEW

**Review by bombsimon — COMMENTED** [review]
The docs (upstream and our [fork](https://github.com/golangci/misspell#why-is-it-making-mistakes-or-missing-items-in-golang-files) states that this is case sensitive. Should we update the docs in our fork? If not, this sounds like the expected behaviour to me.

**Comment by ldez** [comment]
In fact, the `ignore-words` are not related to [this section](https://github.com/golangci/misspell#why-is-it-making-mistakes-or-missing-items-in-golang-files)

`ignore-words` is related to [`Replacer.RemoveRule()`](https://github.com/golangci/misspell/blob/e477db52be0e9dfc112aad71d51585d3d4167fdb/replace.go#LL59C1-L69C1).
`Replacer.RemoveRule()` uses [`inArray()`](https://github.com/golangci/misspell/blob/e477db52be0e9dfc112aad71d51585d3d4167fdb/replace.go#L19-L26), that check the equality.

The goal of `ignore-words` (the name is bad/wrong) is just to remove a prefined rule, so you need to know the key of this rule. It's just a filter, there is no `Contains` here.

**Comment by ldez** [comment]
Note: a better fix can be to just use `strings.EqualFold` instead of `==` inside the `inArray()` function.

WDYT?

**Review by bombsimon — APPROVED** [review]
Oh, read the wrong section!

I think equal folds is clearer and shows that any casing matches but this works fine as well!

**Pull request merged**
