### PR TITLE
Correct import path of module sourcegraph/go-diff

### PR DESCRIPTION
**Pull request by aofei**
See https://github.com/sourcegraph/go-diff/commit/de643bfad3d9698fdda932817e16d84daf69e91d.

### CODE REVIEW

**Comment by jadekler** [comment]
Hello! This is causing considerable headache for many users. Could you please merge this and push out a new release?

**Comment by jle** [comment]
Can this be merged? Thank you!

**Comment by VojtechVitek** [comment]
cc @jirfag

**Comment by aofei** [comment]
ping @jirfag

**Comment by jirfag** [comment]
thank you! merging

**Comment by 0x13a** [comment]
hi there @jirfag - has this been released? thanks

**Comment by aofei** [comment]
Hi @jirfag, it hasn't been released yet.

Somehow, I believe @jirfag is missing... 🙃 Because it has been more than a month since he posted https://github.com/golangci/golangci-lint/issues/508#issuecomment-485778588. Is there no other maintainer for this project? Only one?

**Pull request merged**
