### PR TITLE
dev: refactor ifs with cmp.Or

### PR DESCRIPTION
**Pull request by alexandear**
The PR refactors applicable `if` statements to use [`cmp.Or`](https://pkg.go.dev/cmp#Or).

See https://blog.carlana.net/post/2024/golang-cmp-or-uses-and-history/

### CODE REVIEW

**Comment by ldez** [comment]
This is an abuse of `cmp.Or`: this is mainly useful when creating a comparison implementation.
The readability and performance of `cmp.Or` are worse than simple `if`.

`cmp.Or` evaluates the 2 parts before comparing them whereas the `if` evaluates the first and the second only if needed, so this is mainly a bad idea to put this everywhere.

**Comment by ccoVeille** [comment]
> I hope the usage of `cmp.Or` will not be wrongly widespread over the Go ecosystem.

Maybe it's time to build a new linter :superhero:

**Comment by ccoVeille** [comment]
> I hope the usage of `cmp.Or` will not be wrongly widespread over the Go ecosystem.

https://github.com/search?q=language%3Ago+%22cmp.Or%28%22&type=code&p=2

Unless I'm wrong, only a few codes are using `cmp.Or`  with "legitimate" things like `cmp.Compare`. The main usage is to provide a coalesce operator ...

**Comment by ccoVeille** [comment]
@alexandear what do you think about adding a new linter in revive about this ?

**Pull request merged**
