### PR TITLE
Update documentation and assets

### PR DESCRIPTION
**Pull request by golangci-releaser**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by ldez** [comment]
@jirfag @ernado could you sign the CLA with the @golangci-releaser account? thank you.

**Comment by Nivl** [comment]
Should we just make another PR and cherry-pick the commits?

**Comment by ldez** [comment]
Yes, but we will wait a bit because if we don't handle that now the same will occurs the next time.

**Comment by Nivl** [comment]
Not necessarily, that's 2 actions that can be done in parallel. We're blocked today, so we can do another PR ourselves and in the meantime, someone at @golangci/core-team can deal with the CLA issue (we can open a new issue and assign it to them). I'm not sure what their availabilities look like, but if they're swamp right now, I'd rather not block anything (1.39 can't be used with our Action until this PR is merged).

**Comment by ldez** [comment]
@Nivl I opened #1876.

We will keep this PR open until the bot has signed the CLA

**Comment by SVilgelm** [comment]
@ernado could you ping @jirfag to sign the CLA for the bot?

**Comment by ernado** [comment]
Will PM once again

**Comment by SVilgelm** [comment]
@jirfag Could you please sing CLA for the @golangci-releaser bot? @ernado please ping @jirfag one more time

**Comment by ldez** [comment]
I close the old PR and keep only the latest. We still hope that @jirfag will fix the problem.

**Pull request closed without merging**
