### PR TITLE
Add errname linter

### PR DESCRIPTION
**Pull request by Antonboom**
Hello!

https://github.com/Antonboom/errname

I'm sorry, I am confused about `goanalysis.LoadMode` and `linter.Preset*`. I don't see any documentation that explains which constants are best for your linter.

Thank u for any suggestions.

### CODE REVIEW

**Comment by Antonboom** [comment]
@ldez, also, I am not native english speaker.

Maybe u can suggest more pleasant form for error message than
```
the sentinel error `EndOfFileError` should be of the form ErrXxx
the error type `someTypeWithoutPtr` should be of the form xxxError
```

(especially interested in articles)

**Comment by ldez** [comment]
Hello @Antonboom, could you sign the CLA?

**Comment by Antonboom** [comment]
@ldez, done

**Comment by Antonboom** [comment]
@ldez, something else?

**Comment by ldez** [comment]
Sorry, it's always the same thing: a day has only 24h :smile_cat: 
I will spend some time on your PR this weekend.

**Comment by ldez** [comment]
@Antonboom take a look to https://github.com/Antonboom/errname/pull/2

**Comment by Antonboom** [comment]
@ldez, thanks!

Merged. This MR updated too

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
