### PR TITLE
Add go1.16 support

### LINKED ISSUE #1725: Install golangci-lint on Apple Silicon (darwin-arm64)
The release didn't build golangci-lint-1.36.0-darwin-arm64.tar.gz, so it will return HTTP 404 when download golangci-lint on Apple M1

Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>v1.36.0</summary>

```console
% curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin -d v1.36.0

golangci/golangci-lint info checking GitHub for tag 'v1.36.0'
golangci/golangci-lint debug http_download https://github.com/golangci/golangci-lint/releases/v1.36.0
golangci/golangci-lint info found version: 1.36.0 for v1.36.0/darwin/arm64
golangci/golangci-lint debug downloading files into /var/folders/v3/qzc5zjs93jxfyt_0z9r82g2m0000gp/T/tmp.S0oiIwga
golangci/golangci-lint debug http_download https://github.com/golangci/golangci-lint/releases/download/v1.36.0/golangci-lint-1.36.0-darwin-arm64.tar.gz
golangci/golangci-lint debug http_download_curl received HTTP status 404
```

</details>

<details><summary>Config file</summary>
N/A
</details>

<details><summary>Go environment</summary>

```console
% go version && go env
go version go1.16rc1 darwin/arm64
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/pichu/Library/Caches/go-build"
GOENV="/Users/pichu/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/pichu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/pichu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.15.7_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.15.7_1/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16rc1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/pichu/gitlocalrepos/poa/Ptt-backend/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v3/qzc5zjs93jxfyt_0z9r82g2m0000gp/T/go-build2816074119=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

<details><summary>Verbose output of running</summary>
N/A
</details>

### PR DESCRIPTION
**Pull request by ldez**
- drop go1.13
- add go1.16

We have to wait for the new alpine Docker image for go1.16 before merging the PR.
https://github.com/docker-library/official-images/pull/9639

Also, we will have to update the CI check requirements settings in GitHub

Fixes #1725

### CODE REVIEW

**Comment by ldez** [comment]
The error message returned by govet has been changed, so I don't know how we will handle that to be able to run the tests on go1.14 and go1.15

**Comment by ldez** [comment]
@ernado could you update the CI check requirements settings in GitHub?

**Comment by ernado** [comment]
Hey @ldez, I've updated settings, now it is required to pass go1.{14,15,16} and the go1.13 requirement was dropped.

**Review by ernado — APPROVED** [review]

**Comment by sayboras** [comment]
maybe it's time to cut off a new release as well ? I have been building from source for ttime being :(

**Comment by sayboras** [comment]
The related changes in goreleaser https://github.com/goreleaser/goreleaser/pull/1956 and https://github.com/goreleaser/goreleaser/releases/tag/v0.156.1.

Seems like it will just work without any update required for .goreleaser.yaml

**Comment by ldez** [comment]
@sayboras I agree, can we merge #1739 before?

**Pull request merged**
