### PR TITLE
Remove comparison to gometalinter in benchmarks

### PR DESCRIPTION
**Pull request by pkuca**
- Remove gometalinter run from bench test
- Clone remote tool repo to local repository in bench test

### CODE REVIEW

**Comment by ldez** [comment]
As it's a breaking change, we cannot remove the linter like that.

**Comment by SVilgelm** [comment]
so, it's archived, but the lates code a completely compatible with golangci-lint, personally I never seen any suggestions from this linter, but it's enabled.
Instead of removing the linter, let's mark it as deprecated and printing a warning message.

**Comment by pkuca** [comment]
"mark it as deprecated and printing a warning message" - what's the recommended way to do both of those things? I may have missed other occurrences while searching.

**Comment by ernado** [comment]
I'm not sure that we done such thing before, so there can be no examples.

**Comment by SVilgelm** [comment]
@pkuca @ernado please see the #1755 PR, I added a feature to mark the linters as deprecated.

**Comment by SVilgelm** [comment]
@pkuca The PR #1755 is merged, so we marked the interfacer as deprecated. Please rebase this PR, but don't delete interfacer

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
