### PR TITLE
Add new linter gomockcontrollerfinish

### LINKED ISSUE #3223: New linter: flag unnecessary calls to `Finish` on `gomock.Controller`s in Go 1.14+
### Your feature request related to a problem? Please describe.

As highlighted in https://pkg.go.dev/github.com/golang/mock/gomock#NewController:

> New in go1.14+, if you are passing a *testing.T into this function you no longer need to call ctrl.Finish() in your test methods.

### Describe the solution you'd like.

A linting rule that can flag when we're unnecessarily calling `.Finish`, when using a Go version of 1.14+

### Describe alternatives you've considered.

N/A

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by hendrywiranto**
Hello, 
I'd like to add new linter
https://github.com/hendrywiranto/gomockcontrollerfinish

Closes #3223

Currently, it's only checks whether an unnecessary call to `.Finish()` on `gomock.Controller` exists

Note: I'm open to renaming for more general use such as `gomocklint` to support another linting rule for `gomock` in the future

### CODE REVIEW

**Comment by ldez** [comment]
In order for a pull request adding a linter to be reviewed, the linter and the PR must follow some requirements.

- [ ] The CLA must be signed

### Pull Request Description

- [ ] It must have a link to the linter repository.
- [ ] It must provide a short description of the linter.

### Linter

- [ ] It must not be a duplicate of another linter or a rule of a linter. (the team will help to verify that)
- [ ] It must have a valid license (AGPL is not allowed) and the file must contain the required information by the license, ex: author, year, etc.
- [ ] The linter repository must have a CI and tests.
- [ ] It must use [`go/analysis`](https://golangci-lint.run/contributing/new-linters/).
- [ ] It must have a valid tag, ex: `v1.0.0`, `v0.1.0`.
- [ ] It must not contain `init()`.
- [ ] It must not contain `panic()`.
- [ ] It must not contain `log.fatal()`, `os.exit()`, or similar.
- [ ] It must not modify the AST.
- [ ] It must not have false positives/negatives. (the team will help to verify that)
- [ ] It must have tests inside golangci-lint.

### The Linter Tests Inside Golangci-lint

- [ ] They must have at least one std lib import.
- [ ] They must work with `T=<name of the linter test file>.go make test_linters`. (the team will help to verify that)

### `.golangci.reference.yml`

- [ ] The linter must be added to the list of available linters (alphabetical case-insensitive order).
    - `enable` and `disable` options
- [ ] If the linter has a configuration, the exhaustive configuration of the linter must be added (alphabetical case-insensitive order)
    - The values must be different from the default ones.
    - The default values must be defined in a comment.
    - The option must have a short description.

### Others Requirements

- [ ] The files (tests and linter) inside golangci-lint must have the same name as the linter.
- [ ] The `.golangci.yml` of golangci-lint itself must not be edited and the linter must not be added to this file.
- [ ] The linters must be sorted in the alphabetical order (case-insensitive) in the `Manager.GetAllSupportedLinterConfigs(...)` and `.golangci.reference.yml`.
- [ ] The load mode (`WithLoadMode(...)`):
    - if the linter doesn't use types: `goanalysis.LoadModeSyntax`
    - `goanalysis.LoadModeTypesInfo` required `WithLoadForGoAnalysis()` in the `Manager.GetAllSupportedLinterConfigs(...)`
- [ ] The version in `WithSince(...)` must be the next minor version (`v1.X.0`) of golangci-lint.
- [ ] `WithURL()` must contain the URL of the repository.

### Recommendations

- [ ] The linter should not use SSA. (SSA can be a problem with generics)
- [ ] The linter repository should have a readme and linting.
- [ ] The linter should be published as a binary. (useful to diagnose bug origins)

---

The golangci-lint team will edit this comment to check the boxes before and during the review.

The code review will start after the completion of those checkboxes (except for the specific items that the team will help to verify).

If the author of the PR is a member of the golangci-lint team, he should not edit this message.

**This checklist does not imply that we will accept the linter.**

**Comment by Antonboom** [comment]
@hendrywiranto, hello!

I don't want to belittle your work, but before a review there is a simple question – what is the profit from such kind of linters?

1.`Finish` is idempotent and sometimes to see explicit call is more clear for test reader.
2. In the first version of this feature `gomock` had [protection from this](https://github.com/golang/mock/pull/478/files#diff-c486db4ddab54ba34a2f30a3d2e9ae258910b3389b232d3c187b9b5ece1f3917L272-L276), but after this line was deleted because of

> Also, removed logging as after thinking about it more it seems a little aggressive to push the feature onto users.

You ignored my [comment](https://github.com/golangci/golangci-lint/issues/3223#issuecomment-1742027132), but instead of linter I suppose just make contribution in [uber-go/mock](https://github.com/uber-go/mock/blob/7fb6390728f033a2388bae8a91117fd3f6b3142c/gomock/controller.go#L264).

**Comment by hendrywiranto** [comment]
> @hendrywiranto, hello!
> 
> I don't want to belittle your work, but before a review there is a simple question – what is the profit from such kind of linters?

Hi @Antonboom , thanks for the comment!

I think the main benefit is we can have less code in the tests, not only just 1 less line, but also we can completely remove the usage of e.g. `TearDownTest` that only calls this `Finish` method.

Also a little background, I recently saw lots of my coworker still calling `Finish` on their unit tests and I think that it would be nice if this can be tackled by a linter so I won't have to nit on this anymore. That's why I'm interested for taking the issue in the first place. For improvement I'm thinking of making an autofix to make it more useful

> 1.`Finish` is idempotent and sometimes to see explicit call is more clear for test reader. 
> 2. In the first version of this feature `gomock` had [protection from this](https://github.com/golang/mock/pull/478/files#diff-c486db4ddab54ba34a2f30a3d2e9ae258910b3389b232d3c187b9b5ece1f3917L272-L276), but after this line was deleted because of
> 
> > Also, removed logging as after thinking about it more it seems a little aggressive to push the feature onto users.
> 

Thank you for the reference, I'm also aware that `Finish` is idempotent, but seems like calling it explicitly is not necessary anymore since go1.14 as stated in the official docs  

> You ignored my [comment](https://github.com/golangci/golangci-lint/issues/3223#issuecomment-1742027132), but instead of linter I suppose just make contribution in [uber-go/mock](https://github.com/uber-go/mock/blob/7fb6390728f033a2388bae8a91117fd3f6b3142c/gomock/controller.go#L264).

For your comment I actually saw it, sorry it's just I don't know what to respond to it. For the linter itself, it works as long as the controller object is a `gomock.Controller`.

All in all, thank you for the review, I'm still new at go linters and I'm open for feedbacks on this. It's okay if this ends up to look not really useful, I can still use it on my org codebase. I just think it's better if I'm able to add it into this awesome project :)

**Comment by Antonboom** [comment]
> For the linter itself, it works as long as the controller object is a gomock.Controller

Imho, `HasSuffix` is not the good solution. I expected the strict compasion with objects from google and uber packages.
Otherwise false positives from forks are possible.

> but seems like calling it explicitly is not necessary anymore

As I said before I just affected by different situation, when people used to call `Finish` explicitly, so as not to think about the internal hidden logic of the package and the Go version. Sorry 🙏 

> also we can completely remove the usage of e.g. TearDownTest that only calls this Finish method.

Nice point!

> And sorry for asking, can you elaborate what kind contribution do you recommend for `uber-go/mock`?

I meant that you can offer them to return the deleted line with the log, but instead of the log, for example, fail the test.

This is the way of the Go std `testing` package:
```go
func (t *T) Run(name string, f func(t *T)) bool {
	if t.cleanupStarted.Load() {
		panic("testing: t.Run called during t.Cleanup")
	}
// ...

func (c *common) checkFuzzFn(name string) {
	if c.inFuzzFn {
		panic(fmt.Sprintf("testing: f.%s was called inside the fuzz target, use t.%s instead", name, name))
	}
}
// ...

func (t *T) Parallel() {
	if t.isParallel {
		panic("testing: t.Parallel called multiple times")
	}
// ....
```


<br>

P.S. Also it is better to remove this filter

```go
if !isTestFile(pass.Fset.Position(callExpr.Pos()).Filename) {
```
- golangci-lint controls sources to lint
- helpers, base suites, etc. could be not in tests file too

**Comment by hendrywiranto** [comment]
> Imho, `HasSuffix` is not the good solution. I expected the strict compasion with objects from google and uber packages. Otherwise false positives from forks are possible.

Yes it's still possible, I will look for another way of checking this. thanks
 
> I meant that you can offer them to return the deleted line with the log, but instead of the log, for example, fail the test.

Ah I see, appreciate the explanation
Actually about your suggestion, I'm not sure if that's what the community will agree on.
The other day I saw this [deprecation PR](https://github.com/uber-go/mock/pull/50) on Uber's fork and someone said that eventually removing `Finish` completely (or in this case making it fail the test if called explicitly) is not preferable.

https://github.com/uber-go/mock/pull/50#issuecomment-1713179638

> Please don't remove this function. It's needed to use gomock with certain testing frameworks, and removing the function would break those use cases.
> Please also consider reverting the deprecation. If the function is not going to be removed in a future release, it shouldn't be marked deprecated in the first place.
> See https://github.com/uber-go/mock/issues/81 for more details.

Also the deprecation of the method itself is reverted https://github.com/uber-go/mock/pull/85.
  
  
I'm thinking that the users of the framework that still require to call `Finish` can just not enable the linter, while users that don't use any framework (or use framework that still works fine without `Finish`) can still enable it if they wanted to
Quoting the discussion: https://github.com/uber-go/mock/discussions/84#discussion-5620526
> Given that there are valid use cases of Finish, the function should probably not deprecated at all. Instead, documentation could be added explaining that usually (i.e. when not using any test framework) it's not necessary to call that function.



> PS. Also it is better to remove this filter

Noted on the PS. I will adjust it. Thanks

**Comment by hendrywiranto** [comment]
adjusted based on both of your comments @Antonboom 

- [x] `isTestFile` filter removed
- [x] strict comparison with objects from google and uber packages. Not sure if what I'm doing with the check is preferable, but now it's stricter compared to just using `HasSuffix`

**Comment by alexandear** [comment]
I'm not sure if we really need this linter.

A few months ago I pushed changes that deprecated [`ctrl.Finish`](https://github.com/uber-go/mock/pull/50). After this `staticcheck` begins to detect usages of this deprecated function.
But this change breaks [some test frameworks](https://github.com/uber-go/mock/discussions/84) and it was reverted by [the PR](https://github.com/uber-go/mock/pull/85).
So, the `ctrl.Finish` is still needed.

**Comment by hendrywiranto** [comment]
Hi @alexandear, yes I noticed your PR and the discussions around it.

I think other than those test frameworks that you mentioned, people can completely omits it.
That's why I propose to just disable the linter if there is still a need for it.

And on my case, it's quite useful e.g. as I mentioned [here](https://github.com/golangci/golangci-lint/pull/4202#issuecomment-1812691203)
> I think the main benefit is we can have less code in the tests, not only just 1 less line, but also we can completely remove the usage of e.g. TearDownTest that only calls this Finish method.

What do you think?

**Comment by alexandear** [comment]
@hendrywiranto
Yes, I find the linter useful, but it's not worth adding the whole linter that detects usages of only one function in one library.

Perhaps we should consider adding a new rule to the existing linters such as [go-critic](https://github.com/go-critic/go-critic), [revive](https://github.com/mgechev/revive), or [staticcheck](https://github.com/dominikh/go-tools)?

**Comment by ldez** [comment]
> also I wonder how many rules does it take for a linter to be considered worth it?

This rule doesn't really exist, a linter doesn't have to handle several elements/rules.

Your linter is focused on a tiny rule, it's not a major blocker but this questions the relevance of your linter.

**Comment by alexandear** [comment]
It's possible to prevent the usage of `ctrl.Finish` with the [`forbidigo`](https://github.com/golangci/golangci-lint/blob/ce020c6be1b8f9da457436fa9b85f7f54f8107b7/.golangci.reference.yml#L379) linter. Here is the `.golangci-lint.yml` configuration:
```
linters-settings:
    forbid:
      - p: ^gomock.Controller.Finish*
        pkg: ^go.uber.org/mock/gomock$
        msg: "This function is redundant. See https://pkg.go.dev/go.uber.org/mock@v0.2.0/gomock#Controller.Finish"
    analyze-types: true

linters:
  disable-all: true
  enable:
    - forbidigo

exclude-rules:
    - path-except: _test\.go
      linters:
        - forbidigo
```

**Comment by ldez** [comment]
so it's already possible with another linter, we will decline this PR.

**Pull request closed without merging**
