### PR TITLE
go1.22 support

### PR DESCRIPTION
**Pull request by ldez**
This PR is to evaluate and prepare golangci-lint to [go1.22](https://tip.golang.org/doc/go1.22).

This PR will evolve during the beta and RC phases of [go1.22](https://tip.golang.org/doc/go1.22).

**Questions and problems related to go1.22 should be reported in the issue #4273.**

---

_Sponsoring is a good way to sustain open source maintainers: [sponsor me](https://github.com/sponsors/ldez)_

### CODE REVIEW

**Comment by leonklingele** [comment]
fyi: Go 1.22.0 just landed 🚀

**Comment by ldez** [comment]
fyi: we have to wait for the availability of the Docker images of Go.

https://github.com/docker-library/official-images/pulls?q=is%3Apr+label%3Alibrary%2Fgolang

**Review by AlekSi — APPROVED** [review]

**Comment by AlekSi** [comment]
https://github.com/docker-library/official-images/issues/16209#issuecomment-1931696439

**Comment by ldez** [comment]
There is a problem inside the official Docker CI.
The image for amd64 is being built https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/golang/

**Comment by ldez** [comment]
The official Docker image of Go is available, so let's start the release :tada:

**Comment by ldez** [comment]
In fact, the image is still not available, but the Docker CI seems "unstuck" :cry:

**Comment by constantoine** [comment]
Image has started appearing on the Hub

**Pull request merged**
