### PR TITLE
feat: deprecate varcheck, deadcode, and structcheck

### LINKED ISSUE #826: structcheck returns false positives for embedded structs
Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```bash
$ golangci-lint --version
golangci-lint has version v1.21.0 built from (unknown, mod sum: "h1:HxAxpR8Z0M8omihvQdsD3PF0qPjlqYqp2vMJzstoKeI=") on (unknown)
```

</details>

<details><summary>Config file</summary>

```bash
$ cat .golangci.yml
cat: .golangci.yml: No such file or directory
```

</details>

<details><summary>Go environment</summary>

```bash
$ go version && go env
go version go1.13.1 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/valyala/.cache/go-build"
GOENV="/home/valyala/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/valyala/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/valyala/work/go-src"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/valyala/work/go-src/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/valyala/work/VictoriaMetrics/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build974883207=/tmp/go-build -gno-record-gcc-switches"
```

</details>

See false positives here: https://github.com/VictoriaMetrics/VictoriaMetrics/commit/97ce4e03a57825a783a28e25fc88b9a9e9e09c3c/checks?check_suite_id=269491276

### LINKED ISSUE #1517: False positive for structcheck linter
Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
golangci-lint has version 1.32.2 built from 52d26a3 on 2020-11-03T01:15:38Z
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
linters:
  disable-all: true
  enable:
    - structcheck
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
go version go1.15.5 darwin/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/lukasmalkmus/Library/Caches/go-build"
GOENV="/Users/lukasmalkmus/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/lukasmalkmus/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/lukasmalkmus/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go@1.15/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go@1.15/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dy/s6dd70892l35f0444cwt96t40000gn/T/go-build258997589=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

<details><summary>Verbose output of running</summary>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
INFO [config_reader] Config search paths: [./ /Users/lukasmalkmus/Code/OSS/golangci-lint-unused-issue /Users/lukasmalkmus/Code/OSS /Users/lukasmalkmus/Code /Users/lukasmalkmus /Users /] 
INFO [config_reader] Used config file .golangci.yml 
INFO [lintersdb] Active 1 linters: [structcheck]  
INFO [loader] Go packages loading at mode 575 (types_sizes|deps|imports|name|compiled_files|exports_file|files) took 58.89566ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 1.306913ms 
INFO [linters context/goanalysis] analyzers took 411.503µs with top 10 stages: structcheck: 411.503µs 
INFO [runner] Processors filtering stat (out/in): exclude-rules: 1/1, max_per_file_from_linter: 1/1, skip_dirs: 1/1, identifier_marker: 1/1, sort_results: 1/1, nolint: 1/1, diff: 1/1, max_same_issues: 1/1, max_from_linter: 1/1, source_code: 1/1, path_prefixer: 1/1, cgo: 1/1, filename_unadjuster: 1/1, autogenerated_exclude: 1/1, exclude: 1/1, uniq_by_line: 1/1, path_shortener: 1/1, severity-rules: 1/1, path_prettifier: 1/1, skip_files: 1/1 
INFO [runner] processing took 1.266122ms with stages: autogenerated_exclude: 847.753µs, exclude: 106.116µs, path_prettifier: 87.223µs, nolint: 86.367µs, source_code: 57.543µs, identifier_marker: 30.058µs, skip_dirs: 26.597µs, filename_unadjuster: 7.692µs, uniq_by_line: 3.782µs, max_same_issues: 3.429µs, cgo: 2.592µs, path_shortener: 1.914µs, max_from_linter: 1.446µs, max_per_file_from_linter: 796ns, diff: 559ns, exclude-rules: 553ns, skip_files: 546ns, severity-rules: 409ns, sort_results: 385ns, path_prefixer: 362ns 
INFO [runner] linters took 491.719474ms with stages: structcheck: 490.285749ms 
test.go:4:2: `b` is unused (structcheck)
        b string
        ^
INFO File cache stats: 1 entries of total size 102B 
INFO Memory: 7 samples, avg is 71.8MB, max is 71.8MB 
INFO Execution took 598.573223ms
```

</details>

```go
package issue

type a struct {
	b string
}

type A a

var b = A{"b"}

func B() string {
	return b.b
}

```

Thies yields an error which isn't true:

```
test.go:4:2: `b` is unused (structcheck)
        b string
        ^
```

Field `b` is used.

### LINKED ISSUE #1841: Deprecate varcheck, structcheck, and deadcode
### Is your feature request related to a problem?

Currently, by default golangci-lint runs the following linters about unused/dead code:

- `deadcode`
- `structcheck`
- `unused` (`staticcheck`)
- `varcheck`

Those linters, activated by default, are all the linters related to unused/dead code detection.

https://golangci-lint.run/usage/linters/

I created a small sandbox to find the scope of each of these linters.

| linter        | var                | const              | function               | struct                 | struct field       | method             |
|---------------|--------------------|--------------------|------------------------|------------------------|--------------------|--------------------|
| `deadcode`    |                    |                    | :heavy_check_mark: (1) | :heavy_check_mark: (2) |                    |                    |
| `structcheck` |                    |                    |                        |                        | :heavy_check_mark: |                    |
| `varcheck`    | :heavy_check_mark: | :heavy_check_mark: |                        |                        |                    |                    |
| `unused`      | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:     | :heavy_check_mark:     | :heavy_check_mark: | :heavy_check_mark: |

- (1) False-negative on function
- (2) See unused exported struct as unused

<details>
<summary>deadcode</summary>

```console
$ golangci-lint run --no-config --disable-all -Edeadcode --print-issued-lines=false
sub/sub.go:11:7: `unexportedConstUnusedLocally` is unused (deadcode)
sub/sub.go:16:5: `unexportedGlobalUnused` is unused (deadcode)
main.go:29:6: `fn6` is unused (deadcode)
main.go:31:6: `unusedStruct` is unused (deadcode)
main.go:41:6: `ExposedUnusedStruct` is unused (deadcode)
```

</details>

<details>
<summary>structcheck</summary>

```console
$ golangci-lint run --no-config --disable-all -Evarcheck --print-issued-lines=false
sub/sub.go:11:7: `unexportedConstUnusedLocally` is unused (varcheck)
sub/sub.go:16:5: `unexportedGlobalUnused` is unused (varcheck)
```

</details>

<details>
<summary>varcheck</summary>

```console
$ golangci-lint run --no-config --disable-all -Estructcheck --print-issued-lines=false
sub/sub.go:19:2: `unexportedField` is unused (structcheck)
sub/sub.go:24:2: `unexportedField` is unused (structcheck)
main.go:32:2: `unexportedField` is unused (structcheck)
main.go:37:2: `unusedField` is unused (structcheck)
```

</details>

<details>
<summary>unused</summary>

```console
$ golangci-lint run --no-config --disable-all -Eunused --print-issued-lines=false
sub/sub.go:19:2: field `unexportedField` is unused (unused)
sub/sub.go:24:2: field `unexportedField` is unused (unused)
sub/sub.go:16:5: var `unexportedGlobalUnused` is unused (unused)
sub/sub.go:11:7: const `unexportedConstUnusedLocally` is unused (unused)
main.go:51:34: func `unusedStructWithMethods.unexportedMethod` is unused (unused)
main.go:55:34: func `unusedStructWithMethods.ExportedMethod` is unused (unused)
main.go:25:6: func `fn4` is unused (unused)
main.go:27:6: func `fn5` is unused (unused)
main.go:42:2: field `unexportedField` is unused (unused)
main.go:64:32: func `usedStructWithMethods.unexportedMethod` is unused (unused)
main.go:37:2: field `unusedField` is unused (unused)
main.go:46:6: type `unusedStructWithMethods` is unused (unused)
main.go:29:6: func `fn6` is unused (unused)
main.go:31:6: type `unusedStruct` is unused (unused)
```

</details>

### Describe the solution you'd like

- deprecate `varcheck`, `structcheck`, and `deadcode`.
- remove `varcheck`, `structcheck`, and `deadcode` from the default linters

### Describe alternatives you've considered

- deprecate `varcheck`, `structcheck`, and `deadcode`.

or 

- remove `varcheck`, `structcheck`, and `deadcode` from the default linters

#### `varcheck` and `structcheck`

`varcheck` and `structcheck` come from https://github.com/opennota/check.

https://github.com/opennota/check has moved to https://gitlab.com/opennota/check.

And currently, we use a fork https://github.com/golangci/check

The 2 linters are based on the old `golang.org/x/tools/go/loader`

#### `deadcode`

`deadcode` is also a fork https://github.com/golangci/go-misc

It is based on the old `golang.org/x/tools/go/loader`

### PR DESCRIPTION
**Pull request by ldez**
also, remove them from the default linters.

They can be replaced by `unused`.

`varcheck` and `structcheck` have not changed for 3 years. https://github.com/opennota/check / https://gitlab.com/opennota/check
`deadcode` have not changed for 6 years. https://github.com/remyoudompheng/go-misc

All those linters are using the deprecated `golang.org/x/tools/go/loader` API that is deprecated for more than 3 years (this API does not have support for Go modules).

https://github.com/golang/tools/blob/587a15310bddfc939d37cfaa8be8ea4c3808c3f1/go/loader/doc.go#L10-L11

Fixes #1841

issue related to `structcheck`:
Close #1517
Close #826

### CODE REVIEW

**Review by bombsimon — COMMENTED** [review]
I like this change but curious about the reasoning for modifying default linters not being a breaking change. Breaking default behavior is usually a reason to reject suggestions and push them to v2 (f.e.x modifying or changing exclude use defaults) so this feels a bit inconsistent.

Won't `//nolint` directives for non enabled linters yield a warning by `nolintlint`?

**Comment by ldez** [comment]
In fact, `unused` already handles the same things as `varcheck` and `deadcode`.
As `unused` is enabled by default, it's really a breaking change because the feature is still here, just not handled by the same linters.

Another point, as they are in the default linters, deprecation warnings will appear even if you are not using any configuration.

**Comment by bombsimon** [comment]
> In fact, `unused` already handles the same things as `varcheck` and `deadcode`. As `unused` is enabled by default, it's not really a breaking change because the feature is still here, just not handled by the same linters.

Yeah I get that the analysis result might be the same but the change can still result in changes that breaks CI or other workflows.

> Another point, as they are in the default linters, deprecation warnings will appear even if you are not using any configuration.

Yup, and this is a great reason to disable them by default if deprecating, if not that would be a pretty bad user experience.

> yes `nolint` directives will yield some warning, I don't know if this will be a bigger problem than linter changes.

Yeah me neither. Someone running without configuration and `golangci-lint run -Enolintlint` with `//nolint:varcheck` directives will start to get errors by just upgrading version. That to me is a change that I don't feel is in line with previous discussions where this project tend to be pretty restrictive to avoid breaking changes.

Maybe `nolintlint` isn't a big enough problem to block this kind of change, I just wanted to hear your reasoning around it. I feel I want to leave that decision up to you, personally I don't have a big problem to go less restrictive since bumping version always been a pretty controlled change for me where I've worked.

**Review by bombsimon — APPROVED** [review]
Change is good, resonable deprecation. As discussed might introduce breaking changes but I trust your judgment around this change!

**Comment by ejain** [comment]
`unused` detects an unused `const x = 42`, but, unlike `deadcode`, won't flag `const X = 42`.

**Comment by ldez** [comment]
`varcheck` and `structcheck` have not changed for 3 years. https://github.com/opennota/check / https://gitlab.com/opennota/check

So the project is abandoned.

**Pull request merged**
