### PR TITLE
dev: add new source archive

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

> https://goreleaser.com/customization/source/

PTAL @jirfag

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

Can you explain how valuable this PR is to you or the other users?

**Comment by developer-guy** [comment]
I'm trying to add golangci-lint into the [Wolfi OS](https://github.com/wolfi-dev/os/pull/567); while working on this, I've noticed that there was no checksum entry for the source code tarball in the checksums.txt file, so, this PR is going to add it.

**Comment by ldez** [comment]
This is not exactly what your PR is doing: currently we don't "build" a source code tarball, the tarball is provided by GitHub itself for a release it's not related to our release system.

Your PR is adding the source code as a new tarball during the release, the checksum is just a consequence of this addition.

**Comment by developer-guy** [comment]
> Your PR is adding the source code as a new tarball during the release, the checksum is just a consequence of this addition.
yeah, it is going to add a new source archive as a tarball, I've updated it accordingly. Thank you.

**Review by ldez — APPROVED** [review]
LGTM

**Comment by developer-guy** [comment]
Thank you so much for your assistance ☝️ really appreciate it 🫶

**Pull request merged**
