### PR TITLE
feat: add linereturn linter

### PR DESCRIPTION
**Pull request by Ak-Army**
Add [linereturn](https://github.com/Ak-Army/linereturn) linter.

Linter requires a new line before return statements if the previous line in a block is a real statement.

### CODE REVIEW

**Comment by bombsimon** [comment]
Feels like a duplicate of [`nlreturn`](https://github.com/ssgreg/nlreturn)?

**Comment by ldez** [comment]
Yes it's a duplicate.

**Comment by Ak-Army** [comment]
Not the same as nlreturn, but very similar.
The difference is that this linter expects an enter if there is a real statement in the previous line, but forbids an enter if there is only a statement closure.


Examples of incorrect code:

```go
func fooa() int {
    o := []int{0, 1}
    return o[0]
}

func foob(s string) *a {
    o := &a{
     a: s,
    }
	
    return o
}

func fooc() int {
    defer bar()
    return 0
}

func fooe(s string) interface{} {
    o := foob(
        s,
    )
	
    return o
}
```

Examples of correct code:

```go
func fooa() int {
    o := []int{0, 1}
	
    return o[0]
}

func foob(s string) *a {
    o := &a{
        a: s,
    }
    return o
}

func fooc() int {
    defer bar()
    
    return 0
}

func fooe(s string) interface{} {
    o := foob(
        s,
    )
    return o
}
```

**Comment by ccoVeille** [comment]
Maybe you could contribute to [nlreturn](https://github.com/ssgreg/nlreturn) by opening an PR on it ? it could become a setting of it.

**Comment by Ak-Army** [comment]
Thx, i will try that way.

**Pull request closed without merging**
