### PR TITLE
Update source code link

### PR DESCRIPTION
**Pull request by cnmade**
For new user, who want quickly check the source code

### CODE REVIEW

**Comment by bombsimon** [comment]
There's already a link in the sidebar under `Product` that links to GitHub, you don't think this is enough? 
image

**Comment by cnmade** [comment]
image
The important area , why not put source repository link here.

To developers, source code important than twitter, so what you think about it.

**Comment by ldez** [comment]
The menu is enough for me.

**Comment by ldez** [comment]
We agree, so we will decline the PR.

**Pull request closed without merging**
