### PR TITLE
Protect NewFilenameUnadjuster from concurrent map writes

### PR DESCRIPTION
**Pull request by Helcaraxan**
As signalled in #612 there has been another occurrence of concurrent map writes.

This should address the issue by passing a mutex alongside the map and locking it when writing. Given that the concurrent writes are only occurring while the map is being filled we do not need to pass the mutex back as part of the `FilenameUnadjuster` struct. Consumers of this type should protect against concurrency issues themselves when operating on the enclosed map field.

### CODE REVIEW

**Comment by Helcaraxan** [comment]
@jirfag do you need anything from me in order to merge this? Happy to do so if required, just want to make we're not blocked by anything that I can help with. :slightly_smiling_face:

**Comment by michaljemala** [comment]
@Helcaraxan Could we pls get this merged soon-ish? :-)

**Comment by Helcaraxan** [comment]
@michaljemala I do not have write access on the repository so I can't merge it unfortunately, hence my previous question to @jirfag. :disappointed:

**Comment by bombsimon** [comment]
I'll merge this, although I don't know when we will get a new release.

**Comment by Helcaraxan** [comment]
Ah great. Many thanks @bombsimon ! Now I can contribute better. My previous contribution pre-dates the existence of the automator. :slightly_smiling_face:

**Pull request merged**
