### PR TITLE
dev: improve deprecated comments

### PR DESCRIPTION
**Pull request by alexandear**

### CODE REVIEW

**Comment by ldez** [comment]
This deprecation is a bit special, and not handled in this way.

**Comment by bombsimon** [comment]
Wasn't this change just to clarify why it's deprecated/what to use instead to avoid tribal knowledge rather than some process or parsing? At least for me it's better to add some context to deprecation comments even if just for developers.

**Comment by ldez** [comment]
The problem is that the comment is wrong: the GitHub action format is not replaced by another.

**Comment by bombsimon** [comment]
Ah, I see, I misinterpreted your comment! Then it makes a lot more sense to not merge this!

**Comment by alexandear** [comment]
> The problem is that the comment is wrong: the GitHub action format is not replaced by another.

We can add the link to the comment with explanation:
```go
// Deprecated: not needed, see https://github.com/golangci/golangci-lint/issues/4695#issuecomment-2097087189
```

**Pull request closed without merging**
