### PR TITLE
chore: update usestdlibvars

### PR DESCRIPTION
**Pull request by sashamelentyev**

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

we will let the bot update the linter.

**Comment by ldez** [comment]
@sashamelentyev http.NoBody is already handle by another linter, can you remove this option from your linter?

**Comment by sashamelentyev** [comment]
@ldez ok, I remove this. Which linter do this?

**Comment by ldez** [comment]
https://go-critic.com/overview.html#httpNoBody-ref

**Comment by sashamelentyev** [comment]
@ldez done. I public new minor version of usestdlibvars without http.NoBody check

**Pull request closed without merging**
